### ISSUE TITLE
Could not deploy to Heroku - Build error occurred - Shopify Heroku Deploy

### ISSUE THREAD

**Issue by 90stareq** [Shopify/shopify-app-cli#1016]
I did deploy to Heroku earlier for some reason I deleted the .git folder, manually add git and then push the code to my Github repo. Now I am trying to deploy to Heroku (create a new Heroku app)  but couldn't

## Expected behavior

Should deploy Heroku without any issue

## Actual behavior

What actually happens?

> Build error occurred
> Could not deploy to Heroku

## Steps to reproduce the problem

1.Shopify Deploy Heroku

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

## **Error from CLI**
```
shopify deploy heroku
✓ Downloaded Heroku CLI
✓ Installed Heroku CLI
✓ Git repo initialized
✓ Authenticated with Heroku as `mhtareqarz@gmail.com`
? No existing Heroku app found. What would you like to do? (You chose: Create a new Heroku app)
┏━━ Creating new Heroku app… ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ Creating app... done, enigmatic-island-77062                                                                                  
┃ https://enigmatic-island-77062.herokuapp.com/ | https://git.heroku.com/enigmatic-island-77062.git
┗━━ ✓ New Heroku app created ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (2.78s) ━━
✓ Git branch `master` selected for deploy
┏━━ Deploying to Heroku… ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ remote: Compressing source files... done.        
┃ remote: Building source:        
┃ remote: 
┃ remote: -----> Node.js app detected        
┃ remote:                
┃ remote: -----> Creating runtime environment        
┃ remote:                
┃ remote:        NPM_CONFIG_LOGLEVEL=error        
┃ remote:        NODE_ENV=production        
┃ remote:        NODE_MODULES_CACHE=true        
┃ remote:        NODE_VERBOSE=false        
┃ remote:                
┃ remote: -----> Installing binaries        
┃ remote:        engines.node (package.json):  unspecified        
┃ remote:        engines.npm (package.json):   unspecified (use default)        
┃ remote:                
┃ remote:        Resolving node version 12.x...        
┃ remote:        Downloading and installing node 12.20.0...        
┃ remote:        Using default npm version: 6.14.8        
┃ remote:                
┃ remote: -----> Installing dependencies        
┃ remote:        Installing node modules        
┃ remote:                
┃ remote:        > @ampproject/toolbox-optimizer@2.7.0-alpha.1 postinstall /tmp/build_01285868/node_modules/@ampproject/toolbox-optimizer        
┃ remote:        > node lib/warmup.js        
┃ remote:                
┃ remote:        AMP OPTIMIZER Downloaded latest AMP runtime data.        
┃ remote:                
┃ remote:        > fsevents@1.2.13 install /tmp/build_01285868/node_modules/watchpack-chokidar2/node_modules/fsevents        
┃ remote:        > node install.js        
┃ remote:                
┃ remote:                
┃ remote:        Skipping 'fsevents' build as platform linux is not supported        
┃ remote:                
┃ remote:        > sharp@0.26.2 install /tmp/build_01285868/node_modules/sharp        
┃ remote:        > (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)        
┃ remote:                
┃ remote:        info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.0/libvips-8.10.0-linux-x64.tar.br        
┃ remote:                
┃ remote:        > nodemon@2.0.6 postinstall /tmp/build_01285868/node_modules/nodemon        
┃ remote:        > node bin/postinstall || exit 0        
┃ remote:                
┃ remote:        Love nodemon? You can now support the project via the open collective:        
┃ remote:         > https://opencollective.com/nodemon/donate        
┃ remote:                
┃ remote:                
┃ remote:        > husky@4.3.0 install /tmp/build_01285868/node_modules/husky        
┃ remote:        > node husky install        
┃ remote:                
┃ remote:        husky > Setting up git hooks        
┃ remote:        fatal: not a git repository (or any parent up to mount point /)        
┃ remote:        Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).        
┃ remote:        husky > Failed to install        
┃ remote:                
┃ remote:        > husky@4.3.0 postinstall /tmp/build_01285868/node_modules/husky        
┃ remote:        > opencollective-postinstall || exit 0        
┃ remote:                
┃ remote:        added 2372 packages in 32.793s        
┃ remote:                
┃ remote: -----> Build        
┃ remote:        Running build        
┃ remote:                
┃ remote:        > shopify-darkmode-app@1.0.0 build /tmp/build_01285868        
┃ remote:        > NEXT_TELEMETRY_DISABLED=1 next build        
┃ remote:                
┃ remote:        warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://err.sh/next.js/no-cache        
┃ remote:        info  - Creating an optimized production build...        
┃ remote: Warning: Built-in CSS support is being disabled due to custom CSS configuration being detected.        
┃ remote: See here for more info: https://err.sh/next.js/built-in-css-disabled        
┃ remote: 
┃ remote:        info  - Compiled successfully        
┃ remote:        info  - Collecting page data...        
┃ remote: 
┃ remote: > Build error occurred        
┃ remote: TypeError: Cannot read property 'toLowerCase' of undefined        
┃ remote:     at pluralize (/tmp/build_01285868/node_modules/mongoose-legacy-pluralize/index.js:85:13)        
┃ remote:     at Object.exports.toCollectionName (/tmp/build_01285868/node_modules/mongoose/lib/utils.js:44:12)        
┃ remote:     at Mongoose.model (/tmp/build_01285868/node_modules/mongoose/lib/index.js:567:13)        
┃ remote:     at Object.36Kt (/tmp/build_01285868/.next/server/pages/index.js:117:58)        
┃ remote:     at __webpack_require__ (/tmp/build_01285868/.next/server/pages/index.js:23:31)        
┃ remote:     at Module.RNiq (/tmp/build_01285868/.next/server/pages/index.js:629:80)        
┃ remote:     at __webpack_require__ (/tmp/build_01285868/.next/server/pages/index.js:23:31)        
┃ remote:     at Object.8 (/tmp/build_01285868/.next/server/pages/index.js:125:18)        
┃ remote:     at __webpack_require__ (/tmp/build_01285868/.next/server/pages/index.js:23:31)        
┃ remote:     at /tmp/build_01285868/.next/server/pages/index.js:91:18        
┃ remote:     at Object.<anonymous> (/tmp/build_01285868/.next/server/pages/index.js:94:10)        
┃ remote:     at Module._compile (internal/modules/cjs/loader.js:999:30)        
┃ remote:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)        
┃ remote:     at Module.load (internal/modules/cjs/loader.js:863:32)        
┃ remote:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)        
┃ remote:     at Module.require (internal/modules/cjs/loader.js:887:19) {        
┃ remote:   type: 'TypeError'        
┃ remote: }        
┃ remote: npm ERR! code ELIFECYCLE        
┃ remote: npm ERR! errno 1        
┃ remote: npm ERR! shopify-darkmode-app@1.0.0 build: `NEXT_TELEMETRY_DISABLED=1 next build`        
┃ remote: npm ERR! Exit status 1        
┃ remote: npm ERR!         
┃ remote: npm ERR! Failed at the shopify-darkmode-app@1.0.0 build script.        
┃ remote: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.        
┃ remote: 
┃ remote: npm ERR! A complete log of this run can be found in:        
┃ remote: npm ERR!     /tmp/npmcache.y2KKm/_logs/2020-12-19T23_15_15_695Z-debug.log        
┃ remote: 
┃ remote: -----> Build failed        
┃ remote:                
┃ remote:        We're sorry this build is failing! You can troubleshoot common issues here:        
┃ remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys        
┃ remote:                
┃ remote:        Some possible problems:        
┃ remote:                
┃ remote:        - Node version not specified in package.json        
┃ remote:          https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version        
┃ remote:                
┃ remote:        Love,        
┃ remote:        Heroku        
┃ remote:                
┃ remote:  !     Push rejected, failed to compile Node.js app.        
┃ remote: 
┃ remote:  !     Push failed        
┃ remote: Verifying deploy...
┃ remote: 
┃ remote: !     Push rejected to enigmatic-island-77062.        
┃ remote: 
┃ To https://git.heroku.com/enigmatic-island-77062.git
┃  ! [remote rejected] master -> master (pre-receive hook declined)
┃ error: failed to push some refs to 'https://git.heroku.com/enigmatic-island-77062.git'
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (94.97s) ━━
✗ **Could not deploy to Heroku**
```

- App type: Public
- Operating System: Ubuntu

**Comment by hideokamoto** [comment]
I saw a simillar error to deploy the nodejs app to heroku.

```
 remote:        $ NEXT_TELEMETRY_DISABLED=1 next build        
┃ remote: warn  - React 17.0.1 or newer will be required to leverage all of the upcoming features in Next.js 11. Read more: https://err.sh/next.js/react-version        
┃ remote: 
┃ remote: > Build error occurred        
┃ remote: Error: Cannot find module 'webpack'        
┃ remote: Require stack:        
┃ remote: - /tmp/build_5ca6ba53/node_modules/mini-css-extract-plugin/dist/index.js        
┃ remote: - /tmp/build_5ca6ba53/node_modules/mini-css-extract-plugin/dist/cjs.js        
┃ remote: - /tmp/build_5ca6ba53/node_modules/@zeit/next-css/css-loader-config.js        
┃ remote: - /tmp/build_5ca6ba53/node_modules/@zeit/next-css/index.js        
┃ remote: - /tmp/build_5ca6ba53/next.config.js        
┃ remote: - /tmp/build_5ca6ba53/node_modules/next/dist/next-server/server/config.js        
┃ remote: - /tmp/build_5ca6ba53/node_modules/next/dist/build/index.js        
┃ remote: - /tmp/build_5ca6ba53/node_modules/next/dist/cli/next-build.js        
┃ remote: - /tmp/build_5ca6ba53/node_modules/next/dist/bin/next        
┃ remote:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)        
┃ remote:     at Function.Module._load (internal/modules/cjs/loader.js:725:27)        
┃ remote:     at Module.require (internal/modules/cjs/loader.js:952:19)        
┃ remote:     at require (internal/modules/cjs/helpers.js:88:18)        
┃ remote:     at Object.<anonymous> (/tmp/build_5ca6ba53/node_modules/mini-css-extract-plugin/dist/index.js:7:16)        
┃ remote:     at Module._compile (internal/modules/cjs/loader.js:1063:30)        
┃ remote:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)        
┃ remote:     at Module.load (internal/modules/cjs/loader.js:928:32)        
┃ remote:     at Function.Module._load (internal/modules/cjs/loader.js:769:14)        
┃ remote:     at Module.require (internal/modules/cjs/loader.js:952:19)        
┃ remote:     at require (internal/modules/cjs/helpers.js:88:18)        
┃ remote:     at Object.<anonymous> (/tmp/build_5ca6ba53/node_modules/mini-css-extract-plugin/dist/cjs.js:3:18)        
┃ remote:     at Module._compile (internal/modules/cjs/loader.js:1063:30)        
┃ remote:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)        
┃ remote:     at Module.load (internal/modules/cjs/loader.js:928:32)        
┃ remote:     at Function.Module._load (internal/modules/cjs/loader.js:769:14) {        
┃ remote:   code: 'MODULE_NOT_FOUND',        
┃ remote:   requireStack: [        
┃ remote:     '/tmp/build_5ca6ba53/node_modules/mini-css-extract-plugin/dist/index.js',        
┃ remote:     '/tmp/build_5ca6ba53/node_modules/mini-css-extract-plugin/dist/cjs.js',        
┃ remote:     '/tmp/build_5ca6ba53/node_modules/@zeit/next-css/css-loader-config.js',        
┃ remote:     '/tmp/build_5ca6ba53/node_modules/@zeit/next-css/index.js',        
┃ remote:     '/tmp/build_5ca6ba53/next.config.js',        
┃ remote:     '/tmp/build_5ca6ba53/node_modules/next/dist/next-server/server/config.js',        
┃ remote:     '/tmp/build_5ca6ba53/node_modules/next/dist/build/index.js',        
┃ remote:     '/tmp/build_5ca6ba53/node_modules/next/dist/cli/next-build.js',        
┃ remote:     '/tmp/build_5ca6ba53/node_modules/next/dist/bin/next'        
┃ remote:   ]        
┃ remote: }        
┃ remote: error Command failed with exit code 1.        
┃ remote:        info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.        
┃ remote: 
┃ remote: -----> Build failed        
┃ remote:                
┃ remote:        We're sorry this build is failing! You can troubleshoot common issues here:        
┃ remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys        
┃ remote:                
┃ remote:        Some possible problems:        
┃ remote:                
┃ remote:        - Node version not specified in package.json        
┃ remote:          https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version        
┃ remote:                
┃ remote:        Love,        
┃ remote:        Heroku        
┃ remote:                
┃ remote:  !     Push rejected, failed to compile Node.js app.        
┃ remote: 
┃ remote:  !     Push failed        
┃ remote: Verifying deploy...
┃ remote: 
┃ remote: !     Push rejected to ancient-harbor-15258.        
┃ remote: 
```

**Comment by paulomarg** [comment]
@hideokamoto, I believe in your case you need to add `webpack` to your `packages.json` file, the node app is currently lacking that import.

As for @90stareq's issue, based on the stack trace it looks like you're hitting an issue in code that uses mongoose, which isn't required by the initial app. This looks like a possible bug in your code, so unfortunately there is not much we can do to help.

**Comment by hideokamoto** [comment]
In my case, my app has create by this cli "shopify create node", and nothing to change.
If your idea is true, I need to ask you "Why does not webpack added in the template?"

**Comment by paulomarg** [comment]
This is a recent issue with the CLI app, and we're fixing it soon!

**Comment by hideokamoto** [comment]
Thanks for good information!
I've tried to downgrade the nextjs version from 10 to 9.
And I've succeeded to deploy it to heroku.

```bash
$ npm install --save next@9
$ git add package.json package-lock.json
$ shopify deploy heroku┃ remote:                
┃ remote: -----> Build succeeded!        
┃ remote:  !     Unmet dependencies don't fail yarn install but may cause runtime issues        
┃ remote:        https://github.com/npm/npm/issues/7494        
┃ remote: 
┃ remote: -----> Discovering process types        
┃ remote:        Procfile declares types     -> (none)        
┃ remote:        Default types for buildpack -> web        
┃ remote: 
┃ remote: -----> Compressing...        
┃ remote:        Done: 60.8M        
┃ remote: -----> Launching...        
┃ remote:        Released v3        
┃ remote:        https://xxxxx.herokuapp.com/ deployed to Heroku        
┃ remote: 
┃ remote: Verifying deploy... done.        
┃ To https://git.heroku.com/ancient-harbor-15258.git
┃  * [new branch]      master -> master
┃ Branch 'master' set up to track remote branch 'master' from 'heroku'.
```
```

**Comment by paulomarg** [comment]
That's great @hideokamoto! Just a note that, if you want to continue using next v10+, you can also add `webpack` as a dependency to your project and it should also work.

**Comment by hideokamoto** [comment]
Okay, I'll try to use v10 next time.
Thanks a lot!!!
