### ISSUE TITLE
Tests fail `NameError: uninitialized constant Minitest`

### ISSUE THREAD

**Issue by esquinas** [Shopify/shopify-app-cli#1019]
# Issue summary

Running rails tests after creating a Shopify app fails. Error message and traceback seem to not have anything to do with actual tests. It looks like a misconfiguration problem of the test environment.

## Expected behavior

To run some test code.

## Actual behavior

Rails is aborted immediately.

<details>
[WARNING] Could not load command "rails/commands/test/test_command". Error: uninitialized constant Rails::Minitest.
/home/.../.rvm/gems/ruby-2.7.1/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:80:in `block in load_missing_constant'
/home/.../.rvm/gems/ruby-2.7.1/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:9:in `without_bootsnap_cache'
/home/.../.rvm/gems/ruby-2.7.1/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:80:in `rescue in load_missing_constant'
/home/.../.rvm/gems/ruby-2.7.1/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:59:in `load_missing_constant'
/home/.../.rvm/gems/ruby-2.7.1/gems/railties-6.1.0/lib/rails/test_unit/reporter.rb:7:in `<module:Rails>'
/home/.../.rvm/gems/ruby-2.7.1/gems/railties-6.1.0/lib/rails/test_unit/reporter.rb:6:in `<main>'
/home/.../.rvm/gems/ruby-2.7.1/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/.../.rvm/gems/ruby-2.7.1/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/.../.rvm/gems/ruby-2.7.1/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/.../.rvm/gems/ruby-2.7.1/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/.../.rvm/gems/ruby-2.7.1/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/.../.rvm/gems/ruby-2.7.1/gems/railties-6.1.0/lib/rails/commands/test/test_command.rb:5:in `<main>'
/home/.../.rvm/gems/ruby-2.7.1/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/.../.rvm/gems/ruby-2.7.1/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/.../.rvm/gems/ruby-2.7.1/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/.../.rvm/gems/ruby-2.7.1/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/.../.rvm/gems/ruby-2.7.1/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/.../.rvm/gems/ruby-2.7.1/gems/railties-6.1.0/lib/rails/command/behavior.rb:44:in `block (2 levels) in lookup'
/home/.../.rvm/gems/ruby-2.7.1/gems/railties-6.1.0/lib/rails/command/behavior.rb:40:in `each'
/home/.../.rvm/gems/ruby-2.7.1/gems/railties-6.1.0/lib/rails/command/behavior.rb:40:in `block in lookup'
/home/.../.rvm/gems/ruby-2.7.1/gems/railties-6.1.0/lib/rails/command/behavior.rb:39:in `each'
/home/.../.rvm/gems/ruby-2.7.1/gems/railties-6.1.0/lib/rails/command/behavior.rb:39:in `lookup'
/home/.../.rvm/gems/ruby-2.7.1/gems/railties-6.1.0/lib/rails/command.rb:76:in `find_by_namespace'
/home/.../.rvm/gems/ruby-2.7.1/gems/railties-6.1.0/lib/rails/command.rb:48:in `invoke'
/home/.../.rvm/gems/ruby-2.7.1/gems/railties-6.1.0/lib/rails/commands.rb:18:in `<main>'
/home/.../.rvm/gems/ruby-2.7.1/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/.../.rvm/gems/ruby-2.7.1/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/.../.rvm/gems/ruby-2.7.1/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/.../.rvm/gems/ruby-2.7.1/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/.../.rvm/gems/ruby-2.7.1/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
bin/rails:4:in `<main>'
rails aborted!
NameError: uninitialized constant Minitest
Did you mean?  MiniMime
/home/.../example_shopi_app/test/test_helper.rb:3:in `<main>'
/home/.../example_shopi_app/test/channels/application_cable/connection_test.rb:1:in `<main>'
Tasks: TOP => test
(See full trace by running task with --trace)
</details>

## Steps to reproduce the problem

1. Run `shopify create`
1. Follow instructions, select "Ruby on Rails", then "Custom app", then a development store, then select any database (tested with Sqlite3, PG, made no difference)
1. Run `rails test`

## Reduced test case

It's pretty reduced already, I think.

## Specifications

- App type: Rails 6.1.0 created via shopify-app-cli
- Operating System: Linux Mint 19.3 Tricia
- Shell: GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)
- Ruby version (ruby -v): ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]

Thanks.

**Comment by esquinas** [comment]
Sorry, it was an issue with RVM
