### ISSUE TITLE
Shopify Serve doesn't work | This command ran with ID: 88447

### ISSUE THREAD

**Issue by 90stareq** [Shopify/shopify-app-cli#1020]
# Issue summary

This is my first install on w10. Shopify create node worked properly but shopify serve is not working

## Expected behavior

Should start the development server

## Actual behavior

What actually happens?

**Here is the error code**

```
shopify serve
This command ran with ID: 88447
Please include this information in any issues/report along with relevant logs
Traceback (most recent call last):
        27: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.5.0/bin/shopify:32:in `<main>'
        26: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.5.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        25: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.5.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        24: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.5.0/bin/shopify:33:in `block in <main>'
        23: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.5.0/lib/shopify-cli/core/entry_point.rb:42:in `call'
        22: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.5.0/lib/shopify-cli/core/monorail.rb:32:in `log'
        21: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.5.0/lib/shopify-cli/core/entry_point.rb:43:in `block in call'
        20: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.5.0/lib/shopify-cli/core/executor.rb:15:in `call'
        19: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        18: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        17: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        16: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        15: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        14: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        13: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
        12: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        11: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.5.0/vendor/deps/cli-ui/lib/cli/ui.rb:172:in `log_output_to'
        10: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
         9: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.5.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
         8: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
         7: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.5.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
         6: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.5.0/lib/shopify-cli/command.rb:25:in `call'
         5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.5.0/lib/project_types/node/commands/serve.rb:15:in `call'
         4: from C:/Ruby27-x64/lib/ruby/2.7.0/forwardable.rb:235:in `start'
         3: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.5.0/lib/shopify-cli/tunnel.rb:66:in `start'
         2: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.5.0/lib/shopify-cli/tunnel.rb:162:in `start_ngrok'
         1: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.5.0/lib/shopify-cli/process_supervision.rb:70:in `start'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/shopify-cli-1.5.0/lib/shopify-cli/process_supervision.rb:70:in `spawn': Exec format error - "C:/Users/mhtareq/AppData/Local/shopify/ngrok" http -inspect=false -log=stdout -log-level=debug 8081 (Errno::ENOEXEC)
```

## Specifications

- App type: Public
- Operating System: Windows 10
- Shell: VS Code terminal
- Ruby version (ruby -v): ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x64-mingw32]

**Comment by 90stareq** [comment]
i just found out the solution
issue was, the installed version of ngrok wasn't compatible so i installed ngrok manually
