### ISSUE TITLE
app not working

### ISSUE THREAD

**Issue by ragnarok22** [Shopify/shopify-app-cli#1054]
# Issue summary

I created a app following [this tutorial](https://youtu.be/PIXN032XJJ8) with the command `shopify create node` and this create all the necesary files and installed it. I even installed the app into a develop store. But when I clicked in App show `internal server error`
## Expected behavior
I expected see my hello world app

I'm behind a proxy but y setted this in console with  `set https_proxy=http://myproxy.com:3128`. The command `shopify populate products` works fine

## Actual behavior

When I run the server with `shopify serve`, this redirects me to my shop but every time that I try to access to my app show me this error on console

<details>

FetchError: request to https://ragnaroks-storage.myshopify.com/admin/oauth/access_token failed, reason: getaddrinfo ENOTFOUND ragnaroks-storage.myshopify.com
┃       at ClientRequest.<anonymous> (D:\Ragnarok\projects\Node\shopify\talla_app\node_modules\node-fetch\lib\index.js:1461:11)
┃       at ClientRequest.emit (events.js:315:20)
┃       at TLSSocket.socketErrorListener (_http_client.js:469:9)
┃       at TLSSocket.emit (events.js:315:20)
┃       at emitErrorNT (internal/streams/destroy.js:106:8)
┃       at emitErrorCloseNT (internal/streams/destroy.js:74:3)
┃       at processTicksAndRejections (internal/process/task_queues.js:80:21)
</details>

## Specifications

- Browser: Chrome 87.0.4280.141
- Operating System: Windows 10 Pro build 1909

**Comment by andyw8** [comment]
(this is more about the CLI than shopify-app-code so I've transferred it over)

**Comment by mkevinosullivan** [comment]
Not sure if you're still having the error but that seems to indicate that the node process itself is not able to resolve the `ragnaroks-storage.myshopify.com` address, i.e., it's not picking up the proxy setting from the command line.

`shopify serve` runs multiple sub-processes which might mean the `https_proxy` environment variable may not be passed along.  The main command it runs behind the scene is `npm run dev`, which runs the following line from `package.json`
```
    "dev": "cross-env NODE_ENV=development nodemon ./server/index.js --watch ./server/index.js",
```
You could try modifying that line to be something like
```
    "dev": "cross-env HTTPS_PROXY=http://myproxy.com:3128 NODE_ENV=development nodemon ./server/index.js --watch ./server/index.js",
```
and see if it works.
