### ISSUE TITLE
Fails to fetch URL

### ISSUE THREAD

**Issue by sebastianks** [Shopify/shopify-app-cli#1093]
When using the CLI out of the box I get this error:

```
x ngrok tunnel stopped
This command ran with ID: 39413
Please include this information in any issues/report along with relevant logs
Traceback (most recent call last):
        28: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/bin/shopify:32:in `<main>'
        27: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        26: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        25: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/bin/shopify:33:in `block in <main>'
        24: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/core/entry_point.rb:42:in `call'
        23: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/core/monorail.rb:20:in `log'
        22: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/core/entry_point.rb:43:in `block in call'
        21: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/core/executor.rb:15:in `call'
        20: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        19: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        18: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
        17: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        16: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        15: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        14: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
        13: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        12: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        11: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        10: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
         9: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
         8: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
         7: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/command.rb:25:in `call'
         6: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/lib/project_types/node/commands/serve.rb:15:in `call'
         5: from /usr/lib/ruby/2.7.0/forwardable.rb:235:in `start'
         4: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/tunnel.rb:66:in `start'
         3: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/tunnel.rb:169:in `start_ngrok'
         2: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/tunnel.rb:153:in `fetch_url'
         1: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/tunnel.rb:153:in `new'
/home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/tunnel.rb:202:in `initialize': Unable to fetch external url (ShopifyCli::Tunnel::FetchUrlError)
        27: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/bin/shopify:32:in `<main>'
        26: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        25: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        24: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/bin/shopify:33:in `block in <main>'
        23: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/core/entry_point.rb:42:in `call'
        22: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/core/monorail.rb:20:in `log'
        21: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/core/entry_point.rb:43:in `block in call'
        20: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/core/executor.rb:15:in `call'
        19: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        18: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        17: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
        16: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        15: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
        14: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        13: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
        12: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        11: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        10: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
         9: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
         8: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
         7: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
         6: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/command.rb:25:in `call'
         5: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/lib/project_types/node/commands/serve.rb:15:in `call'
         4: from /usr/lib/ruby/2.7.0/forwardable.rb:235:in `start'
         3: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/tunnel.rb:66:in `start'
         2: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/tunnel.rb:169:in `start_ngrok'
         1: from /home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/tunnel.rb:152:in `fetch_url'
/home/sebastian/.local/share/gem/ruby/2.7.0/gems/shopify-cli-1.6.0/lib/shopify-cli/tunnel.rb:156:in `rescue in fetch_url': Unable to fetch external url (ShopifyCli::Tunnel::FetchUrlError)

```

## Specifications

- App type: Public
- Operating System: Arch Linux
- Shell: bash
- Ruby version (ruby -v): ruby 2.7.2p137

**Comment by mllemango** [comment]
Hey @sebastianks, could you outline the steps you took to get to this error?

**Comment by sebastianks** [comment]
@mllemango Sure. I used your CLI to generate a fresh project. Then I ran `shopify serve` and got this error. I did not do a whole lot.

**Comment by sebastianks** [comment]
@mllemango Anything new on this?

**Comment by mkevinosullivan** [comment]
@sebastianks can you run the following command and share the output, please?
```
$ ngrok http -inspect=false -log=stdout -log-level=debug 8081
```

**Comment by sebastianks** [comment]
@mkevinosullivan This is the output of that command.

```
07:15:22 sebastian@sebastian testing → ngrok http -inspect=false -log=stdout -log-level=debug 8081
INFO[03-10|07:16:48] no configuration paths supplied 
INFO[03-10|07:16:48] using configuration at default config path path=/home/sebastian/.ngrok2/ngrok.yml
INFO[03-10|07:16:48] open config file                         path=/home/sebastian/.ngrok2/ngrok.yml err=nil
DBUG[03-10|07:16:48] init storage                             obj=controller mem size=52428800 err=nil
DBUG[03-10|07:16:48] Dialing direct, no proxy                 obj=tunSess
INFO[03-10|07:16:48] run component                            obj=controller comp="signal handler"
INFO[03-10|07:16:48] run component                            obj=controller comp="Tunnel session"
INFO[03-10|07:16:48] run component                            obj=controller comp="memory storage"
INFO[03-10|07:16:48] run component                            obj=controller comp=updater
INFO[03-10|07:16:48] run component                            obj=controller comp=web
INFO[03-10|07:16:48] starting web service                     obj=web addr=127.0.0.1:4040
DBUG[03-10|07:16:48] update check                             obj=updater
EROR[03-10|07:16:48] failed to reconnect session              obj=csess id=9ebccd2e08fe err="dial tcp: lookup tunnel.us.ngrok.com on [::1]:53: read udp [::1]:52115->[::1]:53: read: connection refused"
DBUG[03-10|07:16:48] sleep before reconnect                   obj=csess id=9ebccd2e08fe secs=0
WARN[03-10|07:16:48] failed to check for update               obj=updater err="Post https://update.equinox.io/check: dial tcp: lookup update.equinox.io on [::1]:53: read udp [::1]:60799->[::1]:53: read: connection refused"
EROR[03-10|07:16:49] failed to reconnect session              obj=csess id=9ebccd2e08fe err="dial tcp: lookup tunnel.us.ngrok.com on [::1]:53: read udp [::1]:51413->[::1]:53: read: connection refused"
DBUG[03-10|07:16:49] sleep before reconnect                   obj=csess id=9ebccd2e08fe secs=1
EROR[03-10|07:16:50] failed to reconnect session              obj=csess id=9ebccd2e08fe err="Get https://dns.google.com/resolve?cd=true&name=tunnel.us.ngrok.com&type=A: dial tcp: lookup dns.google.com on [::1]:53: read udp [::1]:44719->[::1]:53: read: connection refused"
DBUG[03-10|07:16:50] sleep before reconnect                   obj=csess id=9ebccd2e08fe secs=1
EROR[03-10|07:16:51] failed to reconnect session              obj=csess id=9ebccd2e08fe err="Get https://s3.amazonaws.com/dns.ngrok.com/tunnel.json: dial tcp: lookup s3.amazonaws.com on [::1]:53: read udp [::1]:57771->[::1]:53: read: connection refused"
DBUG[03-10|07:16:51] sleep before reconnect                   obj=csess id=9ebccd2e08fe secs=2
DBUG[03-10|07:16:55] open stream                              obj=csess id=b3a1eedb58e0 reqtype=0 err=nil
DBUG[03-10|07:16:55] encode request                           obj=csess id=b3a1eedb58e0 sid=3 req="&{Version:[2] ClientId: Extra:0xc4202de000}" err=nil
DBUG[03-10|07:16:55] decoded response                         obj=csess id=b3a1eedb58e0 sid=3 resp="&{Version:2 ClientId:d90f13f1e0cf5006bf6c399dc4baa3ca Error: Extra:map[Version:prod Cookie:ARLG1aPTAWkjWARklE8Oh4WCIzm+VgOT$hfSLRDQsVu/TrPuEzs6t0R77UJ/xJfrPOw74bGKKSLpG7gsEfidZTmIo971H92JvMQf/X1kC0qMaSyqUi3oFMJJPNsQmW2bdEW77rTaSNJe0Gi9lHS6fTG4Dqgj4A7pGlOtmsiNzjlCvk90GmsO6ghOyhoocm1UBj5NJ1IVZGICBwulmA4MUr29eYbWUkg0Eo4svJcDjMqBVb8sAEA== AccountName:daniel@penni.io SessionDuration:0 PlanName:Business]}" err=nil
INFO[03-10|07:16:55] tunnel session started                   obj=tunSess
INFO[03-10|07:16:55] client session established               obj=csess id=9ebccd2e08fe
DBUG[03-10|07:16:55] open stream                              obj=csess id=b3a1eedb58e0 clientid=d90f13f1e0cf5006bf6c399dc4baa3ca reqtype=1 err=nil
DBUG[03-10|07:16:55] encode request                           obj=csess id=b3a1eedb58e0 clientid=d90f13f1e0cf5006bf6c399dc4baa3ca sid=7 req="&{Id: ClientId: Proto:https Opts:0xc42030fa40 Extra:0xc42030bea0}" err=nil
DBUG[03-10|07:16:55] decoded response                         obj=csess id=b3a1eedb58e0 clientid=d90f13f1e0cf5006bf6c399dc4baa3ca sid=7 resp="&{ClientId:d53f97d7b4dfcf4413ede0aeb952ebf7 URL:https://2ba53cbe0243.ngrok.io Proto:https Opts:map[LocalURLScheme: Hostname:2ba53cbe0243.ngrok.io Auth: Subdomain: HostHeaderRewrite:false] Error: Extra:map[Token:hjts9MDyzQVB9hDRTMZMO4qIWwhDg9oc$YQV3Pyx5d59p4pyNE+i4trJw0CbT7qvF3ks+KVIZf6lUYdfkN2df7ThFAaTZkoIEDVvl85vpLGj5761YIJNuafVCX+egcNWI7/aizfNxx1n+GZqYRwachqbho5ln0UqSaBdOtFGnf79e2fmOOiHtlvEuWyUJziblkJqaLenf7ytaI1Q733zROOqCq5kTlFzCzbZIA+7o4aLgmsuLWvvq8jMRF9lywq+Atty8Ysm+unmLiAIisXBRSfGxwWDVNkSfL7OmNu8/GkCNWwOX7g==]}" err=nil
DBUG[03-10|07:16:55] start tunnel listen                      obj=tunSess name=command_line proto=https opts="&{Hostname: Auth: Subdomain:}" err=nil
DBUG[03-10|07:16:55] open stream                              obj=csess id=b3a1eedb58e0 clientid=d90f13f1e0cf5006bf6c399dc4baa3ca reqtype=1 err=nil
DBUG[03-10|07:16:55] encode request                           obj=csess id=b3a1eedb58e0 clientid=d90f13f1e0cf5006bf6c399dc4baa3ca sid=9 req="&{Id: ClientId: Proto:http Opts:0xc42038e6f0 Extra:0xc4201cdb00}" err=nil
DBUG[03-10|07:16:55] decoded response                         obj=csess id=b3a1eedb58e0 clientid=d90f13f1e0cf5006bf6c399dc4baa3ca sid=9 resp="&{ClientId:d96b3fb2af5a0d04ca8409dd74b6fb47 URL:http://2ba53cbe0243.ngrok.io Proto:http Opts:map[Hostname:2ba53cbe0243.ngrok.io Auth: Subdomain: HostHeaderRewrite:false LocalURLScheme:] Error: Extra:map[Token:d6YAUSl8CPUJj66eHgh5SLAwrKyleaa9$alxA//1ntMKZAu0nR9YfAxeBh9Dp08JRv5FiOe3RC6UBj/X+bzJuHweF6ciKVpEm7AgvuP4vllUOkpPLy0z+YAaO9ncTPEp9R7SGJH+mjR2xdvIpyPMkOymvQ/Pw7Lcc/AnGl+VJi4m/e8X94G0Vtpve3D8KN9MT1Oi1OgKYiP3llCD6IGICtjQJCOmfCNHrSGGXkt5rxmNgOURdCxA0A6dzB+ygFkk1tEe8gtZ5OUCS3Uqo40/fqRJ0RG5A1lyIY7g7tSh7FIMv3DR9]}" err=nil
DBUG[03-10|07:16:55] start tunnel listen                      obj=tunSess name="command_line (http)" proto=http opts="&{Hostname:2ba53cbe0243.ngrok.io Auth: Subdomain:}" err=nil
DBUG[03-10|07:17:05] heartbeat received                       obj=csess id=b3a1eedb58e0 clientid=d90f13f1e0cf5006bf6c399dc4baa3ca latency_ms=185
DBUG[03-10|07:17:15] heartbeat received                       obj=csess id=b3a1eedb58e0 clientid=d90f13f1e0cf5006bf6c399dc4baa3ca latency_ms=137
DBUG[03-10|07:17:25] heartbeat received                       obj=csess id=b3a1eedb58e0 clientid=d90f13f1e0cf5006bf6c399dc4baa3ca latency_ms=136
^CINFO[03-10|07:17:35] component stopped                        obj=controller comp="signal handler" err=nil
INFO[03-10|07:17:35] requesting shutdown                      obj=controller
INFO[03-10|07:17:35] component stopped                        obj=controller comp="memory storage" err=nil
INFO[03-10|07:17:35] component stopped                        obj=controller comp=updater err=nil
INFO[03-10|07:17:35] component stopped                        obj=controller comp=web err=nil
INFO[03-10|07:17:35] session closing                          obj=tunSess err=nil
INFO[03-10|07:17:35] component stopped                        obj=controller comp="Tunnel session" err=nil
INFO[03-10|07:17:35] tunnel session closing permanently       obj=tunSess err="not reconnecting, session closed by the client side"
INFO[03-10|07:17:35] all component stopped                    obj=controller
```

**Comment by sebastianks** [comment]
@mkevinosullivan have you had the time to look into this?

**Comment by SYTrofimov** [comment]
I have got the same issue this morning. ngrok seems to start just fine, but then something fails in the shopify cli.

**Comment by mkevinosullivan** [comment]
Apologies, this slipped down my inbox 😞 

This is quite odd, as the command that I asked to run manually is the same command that the CLI runs internally.  In your case, it seems to be fine.

The fundamental issue is that `ngrok` fails to start (`x ngrok tunnel stopped`) right after you attempt `shopify serve`.  That's quite unusual and I can't seem to replicate the conditions that are causing that.  That message should only appear on two occasions: when `shopify tunnel stop` is run, or when `shopify serve` needs to restart a timed-out tunnel.  In your case, the tunnel doesn't have a timeout as you appear to be using an `ngrok` BusinessPlan.

You could try clearing the cache (`$HOME/.cache/shopify/sv/ngrok.*`) and try again.  If it still fails, please share the log file created in the cache - `$HOME/.cache/shopify/sv/ngrok.log`.

**Comment by aasharck** [comment]
I had this same problem. Solved it when I connected to a VPN.

**Comment by sebkolind** [comment]
I haven't been able to solve this, and I honestly don't use the tool anymore. I don't see a need for this to still be open, so I will close it.

Thanks for the people who spent the time on this issue 🙏🏻

**Comment by itsazzad** [comment]
I am facing the same issue. 
Any workaround by this time?

**Comment by Jadeclon** [comment]
I am facing the same issue.
Any workaround?
