### ISSUE TITLE
Product subscription app extension fails to serve with uninitialized constant Extension::Features::ArgoRendererPackage::Gem 

### ISSUE THREAD

**Issue by AkhilKamath** [Shopify/shopify-app-cli#1196]
# Issue summary
Hi, I updated the shopify cli version that I am using from 1.8.0 to latest 1.9.0  today and when I tried to create and serve a product subscription app extension  I get an uninitialised constant ruby error.

## Expected behavior

The app extension should have served successfully

## Actual behavior
shopify serve fails with following error 

<details>
akhil@akhil-HP-Notebook:~/code/loop-app$ shopify serve
┏━━ Serving extension... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (2.49s) ━━
This command ran with ID: 64964
Please include this information in any issues/report along with relevant logs
Traceback (most recent call last):
	32: from /var/lib/gems/2.7.0/gems/shopify-cli-1.9.0/bin/shopify:32:in `<main>'
	31: from /var/lib/gems/2.7.0/gems/shopify-cli-1.9.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	30: from /var/lib/gems/2.7.0/gems/shopify-cli-1.9.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	29: from /var/lib/gems/2.7.0/gems/shopify-cli-1.9.0/bin/shopify:33:in `block in <main>'
	28: from /var/lib/gems/2.7.0/gems/shopify-cli-1.9.0/lib/shopify-cli/core/entry_point.rb:42:in `call'
	27: from /var/lib/gems/2.7.0/gems/shopify-cli-1.9.0/lib/shopify-cli/core/monorail.rb:32:in `log'
	26: from /var/lib/gems/2.7.0/gems/shopify-cli-1.9.0/lib/shopify-cli/core/entry_point.rb:43:in `block in call'
	25: from /var/lib/gems/2.7.0/gems/shopify-cli-1.9.0/lib/shopify-cli/core/executor.rb:15:in `call'
	24: from /var/lib/gems/2.7.0/gems/shopify-cli-1.9.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
	23: from /var/lib/gems/2.7.0/gems/shopify-cli-1.9.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
	22: from /var/lib/gems/2.7.0/gems/shopify-cli-1.9.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	21: from /var/lib/gems/2.7.0/gems/shopify-cli-1.9.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
	20: from /var/lib/gems/2.7.0/gems/shopify-cli-1.9.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
	19: from /var/lib/gems/2.7.0/gems/shopify-cli-1.9.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
	18: from /var/lib/gems/2.7.0/gems/shopify-cli-1.9.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
	17: from /var/lib/gems/2.7.0/gems/shopify-cli-1.9.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
	16: from /var/lib/gems/2.7.0/gems/shopify-cli-1.9.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
	15: from /var/lib/gems/2.7.0/gems/shopify-cli-1.9.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
	14: from /var/lib/gems/2.7.0/gems/shopify-cli-1.9.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
	13: from /var/lib/gems/2.7.0/gems/shopify-cli-1.9.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
	12: from /var/lib/gems/2.7.0/gems/shopify-cli-1.9.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
	11: from /var/lib/gems/2.7.0/gems/shopify-cli-1.9.0/lib/shopify-cli/command.rb:25:in `call'
	10: from /var/lib/gems/2.7.0/gems/shopify-cli-1.9.0/lib/project_types/extension/commands/serve.rb:7:in `call'
	 9: from /usr/lib/ruby/2.7.0/delegate.rb:83:in `method_missing'
	 8: from /var/lib/gems/2.7.0/gems/shopify-cli-1.9.0/lib/project_types/extension/models/specification_handlers/default.rb:46:in `serve'
	 7: from /var/lib/gems/2.7.0/gems/shopify-cli-1.9.0/lib/project_types/extension/features/argo_serve.rb:15:in `call'
	 6: from /var/lib/gems/2.7.0/gems/shopify-cli-1.9.0/vendor/deps/cli-ui/lib/cli/ui/frame.rb:103:in `open'
	 5: from /var/lib/gems/2.7.0/gems/shopify-cli-1.9.0/lib/project_types/extension/features/argo_serve.rb:16:in `block in call'
	 4: from /var/lib/gems/2.7.0/gems/shopify-cli-1.9.0/lib/project_types/extension/features/argo_serve.rb:50:in `yarn_serve_command'
	 3: from /var/lib/gems/2.7.0/gems/shopify-cli-1.9.0/lib/project_types/extension/features/argo_serve.rb:60:in `serve_options'
	 2: from /var/lib/gems/2.7.0/gems/shopify-cli-1.9.0/lib/project_types/extension/features/argo_serve.rb:60:in `tap'
	 1: from /var/lib/gems/2.7.0/gems/shopify-cli-1.9.0/lib/project_types/extension/features/argo_serve.rb:64:in `block in serve_options'
/var/lib/gems/2.7.0/gems/shopify-cli-1.9.0/lib/project_types/extension/features/argo_renderer_package.rb:28:in `supports_uuid_flag?': uninitialized constant Extension::Features::ArgoRendererPackage::Gem (NameError)
</details>

## Steps to reproduce the problem

1. install latest shopify cli version 1.9.0
2. create a product subscription app extension using ```$ shopify create extension --type=PRODUCT_SUBSCRIPTION --name="My subscription extension```
3. cd to the extension app created above and do ```shopify serve```

## Reduced test case

---

## Specifications

- App type: Product subscription extension
- Operating System: Ubuntu 20.04.2 LTS
- Shell:
- Ruby version (ruby -v): ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]

**Comment by cecyc** [comment]
I was not able to reproduce this with version ruby `2.7.0` on the `1.9.0` version of this gem. That said, this check has been removed from the latest version of the gem, so if you update to `1.9.1` you should be good @AkhilKamath.

I am keeping this issue open to ensure if we add this check back in the future, we don't run into the same issue.
