### ISSUE TITLE
Generate Billing and Page not working.

### ISSUE THREAD

**Issue by meiskv** [Shopify/shopify-app-cli#215]
`Sxof:test-project0123x spacey$ shopify generate billing
Enable charging for your app. This command generates the necessary code to call Shopify’s billing API.
  Usage: shopify generate billing
? Which kind of billing? (You chose: recurring billing)
fs.js:81                                                                                                              
  throw new TypeError('Expected options to be either an object or a string, ' +                                       
  ^

TypeError: Expected options to be either an object or a string, but got function instead
    at throwOptionsError (fs.js:81:9)
    at Object.fs.writeFileSync (fs.js:1341:5)
    at transform (/Users/spacey/Desktop/shopify-app/test-project0123x/scripts/transform.js:11:6)
    at receiveArgs (/Users/spacey/Desktop/shopify-app/test-project0123x/scripts/index.js:12:7)
    at Object.<anonymous> (/Users/spacey/Desktop/shopify-app/test-project0123x/scripts/index.js:32:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
Error generating billing_recurring
Sxof:test-project0123x spacey$ shopify generate billing
Enable charging for your app. This command generates the necessary code to call Shopify’s billing API.
  Usage: shopify generate billing
? Which kind of billing? (You chose: one-time billing)
fs.js:81                                                                                                              
  throw new TypeError('Expected options to be either an object or a string, ' +                                       
  ^

TypeError: Expected options to be either an object or a string, but got function instead
    at throwOptionsError (fs.js:81:9)
    at Object.fs.writeFileSync (fs.js:1341:5)
    at transform (/Users/spacey/Desktop/shopify-app/test-project0123x/scripts/transform.js:11:6)
    at receiveArgs (/Users/spacey/Desktop/shopify-app/test-project0123x/scripts/index.js:18:7)
    at Object.<anonymous> (/Users/spacey/Desktop/shopify-app/test-project0123x/scripts/index.js:32:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
Error generating billing_one_time
Sxof:test-project0123x spacey$ shopify generate page ProductList
fs.js:81
  throw new TypeError('Expected options to be either an object or a string, ' +
  ^

TypeError: Expected options to be either an object or a string, but got function instead
    at throwOptionsError (fs.js:81:9)
    at Object.fs.writeFileSync (fs.js:1341:5)
    at generatePage (/Users/spacey/Desktop/shopify-app/test-project0123x/scripts/page/generate-page.js:13:8)
    at receiveArgs (/Users/spacey/Desktop/shopify-app/test-project0123x/scripts/index.js:6:7)
    at Object.<anonymous> (/Users/spacey/Desktop/shopify-app/test-project0123x/scripts/index.js:32:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
Error generating ProductList
Sxof:test-project0123x spacey$ 
`

**Comment by katiedavis** [comment]
Hi @meiskv, just wondering if you've edited the server.js file at all? I'm trying to trouble shoot this with the cli fresh off master and I'm not seeing any issues. Can you let me know what you've been working on within the node app and or the CLI if anything?

**Comment by meiskv** [comment]
Hi @katiedavis ,

Thanks for the response. Sorry I just got back.
I tried creating a new project but as soon as I launch shopify server this is what happens.
<img width="893" alt="Screen Shot 2019-07-12 at 12 38 55 AM" src="https://user-images.githubusercontent.com/939470/61083757-93bb5980-a43d-11e9-83f3-849813837fd0.png">

**Comment by katiedavis** [comment]
Can you let me know which version of node you're using? @meiskv

**Comment by katiedavis** [comment]
I'm going to go ahead and close this but feel free to comment if you run into more issues.
