### ISSUE TITLE
`shopify create` fails on mac default installation

### ISSUE THREAD

**Issue by Ectsang** [Shopify/shopify-app-cli#287]
# Issue summary

On my mac, I did the default install
`eval "$(curl -sS https://raw.githubusercontent.com/Shopify/shopify-app-cli/master/install.sh)"`

Then following the instructions tried to run 
`$ shopify create project myProjectName`

## Expected behavior

Expected to get the default app creation as documented.

## Actual behavior

Got an error complaining about not being able to use gems in shopify-cli.

> [Note] You cannot use gems in shopify-cli.
> [LoadError] dlopen(/usr/local/Cellar/ruby/2.5.3_1/lib/ruby/2.5.0/x86_64-darwin18/readline.bundle, 9): Library not loaded: /usr/local/opt/readline/lib/libreadline.7.dylib
>   Referenced from: /usr/local/Cellar/ruby/2.5.3_1/lib/ruby/2.5.0/x86_64-darwin18/readline.bundle
>   Reason: image not found - /usr/local/Cellar/ruby/2.5.3_1/lib/ruby/2.5.0/x86_64-darwin18/readline.bundle
>        They are disabled.
>        If you are modifying /opt/shopify-cli, please don't.
>        TODO with contribution instructions
> 
> [Note] You cannot use gems in shopify-cli.
> [LoadError] dlopen(/usr/local/Cellar/ruby/2.5.3_1/lib/ruby/2.5.0/x86_64-darwin18/readline.bundle, 9): Library not loaded: /usr/local/opt/readline/lib/libreadline.7.dylib
>   Referenced from: /usr/local/Cellar/ruby/2.5.3_1/lib/ruby/2.5.0/x86_64-darwin18/readline.bundle
>   Reason: image not found - /usr/local/Cellar/ruby/2.5.3_1/lib/ruby/2.5.0/x86_64-darwin18/readline.bundle
>        They are disabled.
>        If you are modifying /opt/shopify-cli, please don't.
>        TODO with contribution instructions
> 
> Traceback (most recent call last):
> 	14: from /Users/eric/.shopify-app-cli/bin/shopify:36:in `<main>'
> 	13: from /Users/eric/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
> 	12: from /Users/eric/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
> 	11: from /Users/eric/.shopify-app-cli/bin/shopify:37:in `block in <main>'
> 	10: from /Users/eric/.shopify-app-cli/lib/shopify-cli/entry_point.rb:12:in `call'
> 	 9: from /Users/eric/.shopify-app-cli/lib/shopify-cli/entry_point.rb:25:in `before_resolve'
> 	 8: from /Users/eric/.shopify-app-cli/lib/shopify-cli/update.rb:10:in `auto_update'
> 	 7: from /Users/eric/.shopify-app-cli/lib/shopify-cli/update.rb:84:in `prompt_for_updates'
> 	 6: from /Users/eric/.shopify-app-cli/bin/shopify:9:in `require'
> 	 5: from /usr/local/Cellar/ruby/2.5.3_1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
> 	 4: from /usr/local/Cellar/ruby/2.5.3_1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
> 	 3: from /Users/eric/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/prompt.rb:3:in `<top (required)>'
> 	 2: from /Users/eric/.shopify-app-cli/bin/shopify:9:in `require'
> 	 1: from /usr/local/Cellar/ruby/2.5.3_1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
> /usr/local/Cellar/ruby/2.5.3_1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': dlopen(/usr/local/Cellar/ruby/2.5.3_1/lib/ruby/2.5.0/x86_64-darwin18/readline.bundle, 9): Library not loaded: /usr/local/opt/readline/lib/libreadline.7.dylib (LoadError)
>   Referenced from: /usr/local/Cellar/ruby/2.5.3_1/lib/ruby/2.5.0/x86_64-darwin18/readline.bundle
>   Reason: image not found - /usr/local/Cellar/ruby/2.5.3_1/lib/ruby/2.5.0/x86_64-darwin18/readline.bundle

## Specifications

- App type: development
- Operating System: macOS 10.14.6
- Shell: bash
- Ruby version (ruby -v): ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]

**Comment by Ectsang** [comment]
Found a workaround here -> https://stackoverflow.com/questions/54261455/library-not-loaded-usr-local-opt-readline-lib-libreadline-7-dylib/54288859

Closing as it's not related to this repo.
