### ISSUE TITLE
Fail to create project due to rails version conflict with shopify_app

### ISSUE THREAD

**Issue by ifyouseewendy** [Shopify/shopify-app-cli#292]
# Issue summary

👋 I'm running into this gem version conflict when `shopify create project di-test-store`. 

```
✔︎ Adding shopify_app gem…
┏━━ Running bundle install... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
┃ Fetching gem metadata from https://rubygems.org/............
┃ Fetching gem metadata from https://rubygems.org/.
┃ Resolving dependencies...
┃ Bundler could not find compatible versions for gem "rails":
┃   In snapshot (Gemfile.lock):
┃     rails (= 5.1.7)
┃
┃   In Gemfile:
┃     rails (~> 5.1.7)
┃
┃     shopify_app (~> 11.0.1) was resolved to 11.0.1, which depends on
┃       rails (> 5.2.1)
┃
┃ Running `bundle update` will rebuild your snapshot from scratch, using only
┃ the gems in your Gemfile, which may resolve the conflict.
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (2.59s) ━━
```

## Expected behavior

Init the rails app successfully

## Actual behavior

What actually happens?

Full error message here 

<details>
```
➜  bin/shopify create project di-test-store
? What type of app project would you like to create? (You chose: rails embedded app)
✓ ngrok tunnel running at  https://a20e16fa.ngrok.io
┏━━ Installing bundler… ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (0.0s) ━━
┏━━ Generating new rails app project in di-test-store... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃       create
┃       create  README.md
┃       create  Rakefile
┃       create  config.ru
┃       create  .gitignore
┃       create  Gemfile
┃          run  git init from "."
┃ Initialized empty Git repository in /Users/wendi/.shopify-app-cli/di-test-store/.git/
┃       create  app
┃       create  app/assets/config/manifest.js
┃       create  app/assets/javascripts/application.js
┃       create  app/assets/javascripts/cable.js
┃       create  app/assets/stylesheets/application.css
┃       create  app/channels/application_cable/channel.rb
┃       create  app/channels/application_cable/connection.rb
┃       create  app/controllers/application_controller.rb
┃       create  app/helpers/application_helper.rb
┃       create  app/jobs/application_job.rb
┃       create  app/mailers/application_mailer.rb
┃       create  app/models/application_record.rb
┃       create  app/views/layouts/application.html.erb
┃       create  app/views/layouts/mailer.html.erb
┃       create  app/views/layouts/mailer.text.erb
┃       create  app/assets/images/.keep
┃       create  app/assets/javascripts/channels
┃       create  app/assets/javascripts/channels/.keep
┃       create  app/controllers/concerns/.keep
┃       create  app/models/concerns/.keep
┃       create  bin
┃       create  bin/bundle
┃       create  bin/rails
┃       create  bin/rake
┃       create  bin/setup
┃       create  bin/update
┃       create  bin/yarn
┃       create  config
┃       create  config/routes.rb
┃       create  config/application.rb
┃       create  config/environment.rb
┃       create  config/secrets.yml
┃       create  config/cable.yml
┃       create  config/puma.rb
┃       create  config/spring.rb
┃       create  config/environments
┃       create  config/environments/development.rb
┃       create  config/environments/production.rb
┃       create  config/environments/test.rb
┃       create  config/initializers
┃       create  config/initializers/application_controller_renderer.rb
┃       create  config/initializers/assets.rb
┃       create  config/initializers/backtrace_silencers.rb
┃       create  config/initializers/cookies_serializer.rb
┃       create  config/initializers/cors.rb
┃       create  config/initializers/filter_parameter_logging.rb
┃       create  config/initializers/inflections.rb
┃       create  config/initializers/mime_types.rb
┃       create  config/initializers/new_framework_defaults_5_1.rb
┃       create  config/initializers/wrap_parameters.rb
┃       create  config/locales
┃       create  config/locales/en.yml
┃       create  config/boot.rb
┃       create  config/database.yml
┃       create  db
┃       create  db/seeds.rb
┃       create  lib
┃       create  lib/tasks
┃       create  lib/tasks/.keep
┃       create  lib/assets
┃       create  lib/assets/.keep
┃       create  log
┃       create  log/.keep
┃       create  public
┃       create  public/404.html
┃       create  public/422.html
┃       create  public/500.html
┃       create  public/apple-touch-icon-precomposed.png
┃       create  public/apple-touch-icon.png
┃       create  public/favicon.ico
┃       create  public/robots.txt
┃       create  test/fixtures
┃       create  test/fixtures/.keep
┃       create  test/fixtures/files
┃       create  test/fixtures/files/.keep
┃       create  test/controllers
┃       create  test/controllers/.keep
┃       create  test/mailers
┃       create  test/mailers/.keep
┃       create  test/models
┃       create  test/models/.keep
┃       create  test/helpers
┃       create  test/helpers/.keep
┃       create  test/integration
┃       create  test/integration/.keep
┃       create  test/test_helper.rb
┃       create  test/system
┃       create  test/system/.keep
┃       create  test/application_system_test_case.rb
┃       create  tmp
┃       create  tmp/.keep
┃       create  tmp/cache
┃       create  tmp/cache/assets
┃       create  vendor
┃       create  vendor/.keep
┃       create  package.json
┃       remove  config/initializers/cors.rb
┃       remove  config/initializers/new_framework_defaults_5_1.rb
┃          run  bundle install
┃ The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
┃ Fetching gem metadata from https://rubygems.org/............
┃ Fetching gem metadata from https://rubygems.org/.
┃ Resolving dependencies.....
┃ Using rake 12.3.3
┃ Using concurrent-ruby 1.1.5
┃ Using i18n 1.6.0
┃ Using minitest 5.11.3
┃ Using thread_safe 0.3.6
┃ Using tzinfo 1.2.5
┃ Using activesupport 5.1.7
┃ Using builder 3.2.3
┃ Using erubi 1.8.0
┃ Using mini_portile2 2.4.0
┃ Using nokogiri 1.10.4
┃ Using rails-dom-testing 2.0.3
┃ Using crass 1.0.4
┃ Using loofah 2.2.3
┃ Using rails-html-sanitizer 1.2.0
┃ Using actionview 5.1.7
┃ Using rack 2.0.7
┃ Using rack-test 1.1.0
┃ Using actionpack 5.1.7
┃ Using nio4r 2.5.1
┃ Using websocket-extensions 0.1.4
┃ Using websocket-driver 0.6.5
┃ Using actioncable 5.1.7
┃ Using globalid 0.4.2
┃ Using activejob 5.1.7
┃ Using mini_mime 1.0.2
┃ Using mail 2.7.1
┃ Using actionmailer 5.1.7
┃ Using activemodel 5.1.7
┃ Using arel 8.0.0
┃ Using activerecord 5.1.7
┃ Using public_suffix 4.0.1
┃ Using addressable 2.7.0
┃ Using bindex 0.8.1
┃ Using bundler 1.17.3
┃ Using byebug 11.0.1
┃ Using regexp_parser 1.6.0
┃ Using xpath 3.2.0
┃ Using capybara 3.29.0
┃ Using childprocess 2.0.0
┃ Using coffee-script-source 1.12.2
┃ Using execjs 2.7.0
┃ Using coffee-script 2.4.1
┃ Using method_source 0.9.2
┃ Using thor 0.20.3
┃ Using railties 5.1.7
┃ Using coffee-rails 4.2.2
┃ Using ffi 1.11.1
┃ Using jbuilder 2.9.1
┃ Using rb-fsevent 0.10.3
┃ Using rb-inotify 0.10.0
┃ Using ruby_dep 1.5.0
┃ Using listen 3.1.5
┃ Using puma 3.12.1
┃ Using sprockets 3.7.2
┃ Using sprockets-rails 3.2.1
┃ Using rails 5.1.7
┃ Using rubyzip 1.2.3
┃ Using sass-listen 4.0.0
┃ Using sass 3.7.4
┃ Using tilt 2.0.9
┃ Using sass-rails 5.0.7
┃ Using selenium-webdriver 3.142.4
┃ Using spring 2.1.0
┃ Using spring-watcher-listen 2.0.1
┃ Using sqlite3 1.4.1
┃ Using turbolinks-source 5.2.0
┃ Using turbolinks 5.2.0
┃ Using uglifier 4.1.20
┃ Using web-console 3.7.0
┃ Bundle complete! 16 Gemfile dependencies, 70 gems now installed.
┃ Use `bundle info [gemname]` to see where a bundled gem is installed.
┃          run  bundle exec spring binstub --all
┃ * bin/rake: Spring inserted
┃ * bin/rails: Spring inserted
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (4.57s) ━━
✔︎ Adding shopify_app gem…
┏━━ Running bundle install... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
┃ Fetching gem metadata from https://rubygems.org/............
┃ Fetching gem metadata from https://rubygems.org/.
┃ Resolving dependencies...
┃ Bundler could not find compatible versions for gem "rails":
┃   In snapshot (Gemfile.lock):
┃     rails (= 5.1.7)
┃
┃   In Gemfile:
┃     rails (~> 5.1.7)
┃
┃     shopify_app (~> 11.0.1) was resolved to 11.0.1, which depends on
┃       rails (> 5.2.1)
┃
┃ Running `bundle update` will rebuild your snapshot from scratch, using only
┃ the gems in your Gemfile, which may resolve the conflict.
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (2.59s) ━━
┏━━ Running shopfiy_app generator... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ Spring is not running
┃ /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/resolver.rb:287:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'shopify_app (~> 11.0.1)' in any of the gem sources listed in your Gemfile. (Bundler::GemNotFound)
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/resolver.rb:255:in `each'
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/resolver.rb:255:in `verify_gemfile_dependencies_are_found!'
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/resolver.rb:49:in `start'
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/resolver.rb:22:in `resolve'
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:258:in `resolve'
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:170:in `specs'
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:237:in `specs_for'
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:226:in `requested_specs'
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:108:in `block in definition_method'
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:20:in `setup'
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/bundler.rb:107:in `setup'
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/setup.rb:20:in `<top (required)>'
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
┃       from /Users/wendi/.gem/ruby/2.5.1/gems/spring-2.1.0/lib/spring/commands.rb:33:in `<module:Spring>'
┃       from /Users/wendi/.gem/ruby/2.5.1/gems/spring-2.1.0/lib/spring/commands.rb:4:in `<top (required)>'
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
┃       from /Users/wendi/.gem/ruby/2.5.1/gems/spring-2.1.0/lib/spring/server.rb:9:in `<top (required)>'
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
┃       from /Users/wendi/.gem/ruby/2.5.1/gems/spring-2.1.0/lib/spring/client/server.rb:9:in `call'
┃       from /Users/wendi/.gem/ruby/2.5.1/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
┃       from /Users/wendi/.gem/ruby/2.5.1/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
┃       from /Users/wendi/.gem/ruby/2.5.1/gems/spring-2.1.0/bin/spring:49:in `<main>'
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (1.06s) ━━
┏━━ Running migrations… ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/resolver.rb:287:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'shopify_app (~> 11.0.1)' in any of the gem sources listed in your Gemfile. (Bundler::GemNotFound)
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/resolver.rb:255:in `each'
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/resolver.rb:255:in `verify_gemfile_dependencies_are_found!'
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/resolver.rb:49:in `start'
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/resolver.rb:22:in `resolve'
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:258:in `resolve'
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:170:in `specs'
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:237:in `specs_for'
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:226:in `requested_specs'
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:108:in `block in definition_method'
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:20:in `setup'
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/bundler.rb:107:in `setup'
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/setup.rb:20:in `<top (required)>'
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
┃       from /Users/wendi/.shopify-app-cli/di-test-store/config/boot.rb:3:in `<top (required)>'
┃       from /Users/wendi/.shopify-app-cli/di-test-store/bin/rails:8:in `require_relative'
┃       from /Users/wendi/.shopify-app-cli/di-test-store/bin/rails:8:in `<top (required)>'
┃       from /Users/wendi/.gem/ruby/2.5.1/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
┃       from /Users/wendi/.gem/ruby/2.5.1/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
┃       from /Users/wendi/.gem/ruby/2.5.1/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
┃       from /Users/wendi/.gem/ruby/2.5.1/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
┃       from /Users/wendi/.gem/ruby/2.5.1/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
┃       from /Users/wendi/.gem/ruby/2.5.1/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
┃       from /Users/wendi/.gem/ruby/2.5.1/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
┃       from /Users/wendi/.shopify-app-cli/di-test-store/bin/spring:15:in `<top (required)>'
┃       from bin/rails:3:in `load'
┃       from bin/rails:3:in `<main>'
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (0.62s) ━━
⭑ Run shopify serve to start the local development server
⭑ Whitelist your development URLs in the Partner Dashboard:
          https://github.com/Shopify/shopify-app-cli#whitelisting-app-redirection-urls
Not running with shell integration. Finalizers: cd:di-test-store
```
</details>

## Steps to reproduce the problem

1. Git clone shopify-app-cli and cd into it
2. shopify create project di-test-store (Since I'm using Fish that there is no compatible version installing the CLI for it, I'm running `bin/shopify` directly)

## Specifications

- App type:
- Operating System: MacOS
- Shell: Fish
- Ruby version (ruby -v): 2.5.1

**Comment by tanema** [comment]
This is most likely because you already have rails 5.1.7 installed on your system. The cli just calls `rails new` and will use what ever rails you already have. You will have to specify the higher version in your gemfile and run bundle again

**Comment by ifyouseewendy** [comment]
Ah, you are right. After reinstalling Rails to another version, it gets passed now. However, I'm getting this error for not finding `dotenv-rails`

```
┏━━ Running shopfiy_app generator... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ Spring is not running
┃     generate  shopify_app:install
┃ Running via Spring preloader in process 54862
┃      gemfile  dotenv-rails
┃       create  config/initializers/shopify_app.rb
┃       create  config/initializers/session_store.rb
┃       create  config/initializers/omniauth.rb
┃       insert  config/initializers/omniauth.rb
┃       create  app/views/layouts/embedded_app.html.erb
┃       create  app/assets/javascripts/shopify_app.js
┃       create  app/views/layouts/_flash_messages.html.erb
┃       create  app/assets/javascripts/flash_messages.js
┃        route  mount ShopifyApp::Engine, at: '/'
┃ Running via Spring preloader in process 54886
┃     generate  shopify_app:shop_model
┃ /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/resolver.rb:287:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'dotenv-rails' in any of the gem sources listed in your Gemfile. (Bundler::GemNotFound)
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/resolver.rb:255:in `each'
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/resolver.rb:255:in `verify_gemfile_dependencies_are_found!'
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/resolver.rb:49:in `start'
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/resolver.rb:22:in `resolve'
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:258:in `resolve'
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:170:in `specs'
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:237:in `specs_for'
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:226:in `requested_specs'
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:108:in `block in definition_method'
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:20:in `setup'
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/bundler.rb:107:in `setup'
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/setup.rb:20:in `<top (required)>'
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
┃       from /opt/rubies/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```

FYI, I manually installed the gem via `gem install dotenv-rails` and it runs to the end successfully now.

**Comment by tanema** [comment]
That is interesting, it must be some sort of failure during bundle install because dotenv is in the shopify_app gemspec.
