### ISSUE TITLE
SHOPIFY_API_SECRET_KEY instead of SHOPIFY_API_SECRET when Generating webhooks in server.js 

### ISSUE THREAD

**Issue by cucrisis** [Shopify/shopify-app-cli#395]
# Issue summary

When using the generate webhooks the cli writes in server.js
```
[...]
  const webhook = receiveWebhook({
    secret: SHOPIFY_API_SECRET_KEY
  });
[...]
```

notice the variable name is **SHOPIFY_API_SECRET_KEY** not **SHOPIFY_API_SECRE** as per `.env`  

## Expected behavior
The secret variable should be ```SHOPIFY_API_SECRET``` as per ```.env``` file
```
[...]
  const webhook = receiveWebhook({
    secret: SHOPIFY_API_SECRET
  });
[...]
```

## Actual behavior

```
┃ (node:67097) UnhandledPromiseRejectionWarning: ReferenceError: SHOPIFY_API_SECRET_KEY is not defined
┃     at /Users/cucrisis/Workspace/proj/self/shopify/testShop/server/server.js:25:13
┃     at processTicksAndRejections (internal/process/task_queues.js:85:5)
┃ (node:67097) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
┃ (node:67097) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by katiedavis** [comment]
Hi @cucrisis please see:
https://github.com/Shopify/shopify-app-cli/issues/387

Did you create your app awhile ago? A few weeks ago we updated that variable to match our Ruby apps.
