### ISSUE TITLE
Shopify Serve in an existing project?

### ISSUE THREAD

**Issue by ekwholesale** [Shopify/shopify-app-cli#396]
Node. Ubuntu. Windows Linux Subsystem.

One thing i've not been able to wrap my head around is if i've made a repo of what i'm working on with the shopify cli and i'm working between more than one machine, it seems i have to make a new project and just pull my files in? this isn't really clarified properly. 

Shopify serve in an existing directory just says it doesn't exist. There isn't any info on how to do this currently.

**Comment by tylerball** [comment]
Great question and we haven't explicitly documented this so we should. The way the CLI knows whether it's in a valid project is by reading a file called `.shopify-cli.yml` that we write during the create command, which looks like this:
```
app_type: :node
```
So as long as you copy over this file to a different system, you can `shopify connect` to generate a .env file.

**Comment by ekwholesale** [comment]
That's great to know. Thank you very much for the insight.

**Comment by syffs** [comment]
> So as long as you copy over this file to a different system, you can `shopify connect` to generate a .env file.

@tylerball creating `.shopify-cli.yml` with the above content and running `shopify connect` ends up with an exception:
```
/home/user/.shopify-app-cli/bin/support/load_shopify.rb:12: warning: Insecure world writable dir /home/user/.shopify-app-cli/bin in PATH, mode 040777
! Don't use connect for production apps
This command ran with ID: 26832
Please include this information in any issues/report along with relevant logs
Traceback (most recent call last):
        26: from /home/user/.shopify-app-cli/bin/shopify:36:in `<main>'
        25: from /home/user/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        24: from /home/user/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        23: from /home/user/.shopify-app-cli/bin/shopify:37:in `block in <main>'
        22: from /home/user/.shopify-app-cli/lib/shopify-cli/core/entry_point.rb:18:in `call'
        21: from /home/user/.shopify-app-cli/lib/shopify-cli/core/monorail/log.rb:29:in `invocation'
        20: from /home/user/.shopify-app-cli/lib/shopify-cli/core/monorail/log.rb:45:in `event'
        19: from /home/user/.shopify-app-cli/lib/shopify-cli/core/entry_point.rb:19:in `block in call'
        18: from /home/user/.shopify-app-cli/lib/shopify-cli/core/executor.rb:17:in `call'
        17: from /home/user/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        16: from /home/user/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `with_traps'
        15: from /home/user/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
        14: from /home/user/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:46:in `block in with_traps'
        13: from /home/user/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:53:in `twrap'
        12: from /home/user/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:47:in `block (2 levels) in with_traps'
        11: from /home/user/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
        10: from /home/user/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `with_logging'
         9: from /home/user/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui.rb:143:in `log_output_to'
         8: from /home/user/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:38:in `block in with_logging'
         7: from /home/user/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:164:in `with_id'
         6: from /home/user/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:39:in `block (2 levels) in with_logging'
         5: from /home/user/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:17:in `block (2 levels) in call'
         4: from /home/user/.shopify-app-cli/lib/shopify-cli/command.rb:24:in `call'
         3: from /home/user/.shopify-app-cli/lib/shopify-cli/commands/connect.rb:11:in `call'
         2: from /home/user/.shopify-app-cli/lib/shopify-cli/commands/connect.rb:36:in `get_app'
         1: from /home/user/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/prompt.rb:85:in `ask'
/home/user/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/prompt.rb:167:in `ask_interactive': insufficient options (ArgumentError)
```
