### ISSUE TITLE
create project error 

### ISSUE THREAD

**Issue by ThomasBonnelye** [Shopify/shopify-app-cli#398]
When I create a project, i have the authentification page then nothing, when i'm retrying the command `shopify create project "name"`, I don't have the connexion page again and can't retry to connect to my account.

```
{{✗ error: Your account was not found. Please sign up at https://partners.shopify.com/signup}}                                       
This command ran with ID: 25934                                                                                                      
Please include this information in any issues/report along with relevant logs
/Users/thomasbonnelye/.shopify-app-cli/lib/shopify-cli/helpers/organizations.rb:7:in `fetch_all': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Users/thomasbonnelye/.shopify-app-cli/lib/shopify-cli/forms/create_app.rb:36:in `organizations'
	from /Users/thomasbonnelye/.shopify-app-cli/lib/shopify-cli/forms/create_app.rb:44:in `organization'
	from /Users/thomasbonnelye/.shopify-app-cli/lib/shopify-cli/forms/create_app.rb:13:in `ask'
	from /Users/thomasbonnelye/.shopify-app-cli/lib/shopify-cli/forms.rb:14:in `ask'
	from /Users/thomasbonnelye/.shopify-app-cli/lib/shopify-cli/commands/create/project.rb:15:in `call'
	from /Users/thomasbonnelye/.shopify-app-cli/lib/shopify-cli/sub_command.rb:12:in `call'
	from /Users/thomasbonnelye/.shopify-app-cli/lib/shopify-cli/command.rb:16:in `call'
	from /Users/thomasbonnelye/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:17:in `block (2 levels) in call'
	from /Users/thomasbonnelye/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:39:in `block (2 levels) in with_logging'
	from /Users/thomasbonnelye/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:164:in `with_id'
	from /Users/thomasbonnelye/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:38:in `block in with_logging'
	from /Users/thomasbonnelye/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui.rb:143:in `log_output_to'
	from /Users/thomasbonnelye/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `with_logging'
	from /Users/thomasbonnelye/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
	from /Users/thomasbonnelye/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:47:in `block (2 levels) in with_traps'
	from /Users/thomasbonnelye/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
	from /Users/thomasbonnelye/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:46:in `block in with_traps'
	from /Users/thomasbonnelye/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
	from /Users/thomasbonnelye/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `with_traps'
	from /Users/thomasbonnelye/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
	from /Users/thomasbonnelye/.shopify-app-cli/lib/shopify-cli/executor.rb:16:in `call'
	from /Users/thomasbonnelye/.shopify-app-cli/lib/shopify-cli/entry_point.rb:16:in `block in call'
	from /Users/thomasbonnelye/.shopify-app-cli/lib/shopify-cli/monorail/log.rb:44:in `event'
	from /Users/thomasbonnelye/.shopify-app-cli/lib/shopify-cli/monorail/log.rb:28:in `invocation'
	from /Users/thomasbonnelye/.shopify-app-cli/lib/shopify-cli/entry_point.rb:15:in `call'
	from /Users/thomasbonnelye/.shopify-app-cli/bin/shopify:37:in `block in <main>'
	from /Users/thomasbonnelye/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	from /Users/thomasbonnelye/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	from /Users/thomasbonnelye/.shopify-app-cli/bin/shopify:36:in `<main>'
```

**Comment by katiedavis** [comment]
Hi @ThomasBonnelye I just want to clarify a few things!

Do you have a partners account at partners.shopify.com? 

When you run shopify create app <name> what shows up now?

**Comment by ThomasBonnelye** [comment]
Hi @katiedavis !

Yes I have a partner account, (I had the page to connect my account and after that a page said Authentification Success. I had this bug after that).
I also tried to delete and reinstall the CLI.

**Comment by katiedavis** [comment]
Interesting! 

So if you try to create an app now, what happens? I'm just trying to see what state you're in ATM

**Comment by ThomasBonnelye** [comment]
Hello ! 
Sorry for my response time, when I try to create an app now that continu to display this error.

**Comment by tanema** [comment]
This error is essentially saying that what you are requesting does not exist (in this scenario it is your organization) However I found your organization called IIM and will look into this further why you are not getting a successful request

**Comment by tanema** [comment]
I don't think that this should be an issue any longer. Please try again.

**Comment by ThomasBonnelye** [comment]
It finally works
