### ISSUE TITLE
Invalid argument @ rb_io_seek

### ISSUE THREAD

**Issue by DaniOldBC** [Shopify/shopify-app-cli#408]
# Issue summary

I've installed shopify-app cli a few days ago and everthing was working fine. Today suddenly I started receving this error when launching 'shopify' command from terminal: 

```
Traceback (most recent call last):
        8: from /Users/username/.shopify-app-cli/bin/shopify:36:in `<main>'
        7: from /Users/username/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        6: from /Users/username/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        5: from /Users/username/.shopify-app-cli/bin/shopify:37:in `block in <main>'
        4: from /Users/username/.shopify-app-cli/lib/shopify-cli/entry_point.rb:11:in `call'
        3: from /Users/username/.shopify-app-cli/lib/shopify-cli/entry_point.rb:23:in `before_resolve'
        2: from /Users/username/.shopify-app-cli/lib/shopify-cli/monorail.rb:36:in `send_events'
        1: from /Users/username/.shopify-app-cli/lib/shopify-cli/log.rb:24:in `tail'
/Users/username/.shopify-app-cli/lib/shopify-cli/log.rb:24:in `seek': Invalid argument @ rb_io_seek - /Users/username/.config/shopify/logs/events.log (Errno::EINVAL)
```

## Specifications

- Operating System: macOS Catalina 10.15.1
- Shell: zsh
- Ruby version (ruby -v):  ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]

**Comment by tanema** [comment]
Hey @DaniOldBC did you figure out what was wrong?

**Comment by DaniOldBC** [comment]
Problem solved by deleting the log file:
```
rm /Users/username/.config/shopify/logs/events.log
```
