### ISSUE TITLE
Shopify command throwing errors

### ISSUE THREAD

**Issue by chris-geelhoed** [Shopify/shopify-app-cli#414]
# Issue summary

Write a short description of the issue here ↓

All shopify commands are throwing this error for me. It was working fine, and now it isn't.

```
Traceback (most recent call last):
	10: from /Users/chris/.shopify-app-cli/bin/shopify:36:in `<main>'
	 9: from /Users/chris/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	 8: from /Users/chris/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	 7: from /Users/chris/.shopify-app-cli/bin/shopify:37:in `block in <main>'
	 6: from /Users/chris/.shopify-app-cli/lib/shopify-cli/entry_point.rb:11:in `call'
	 5: from /Users/chris/.shopify-app-cli/lib/shopify-cli/entry_point.rb:23:in `before_resolve'
	 4: from /Users/chris/.shopify-app-cli/lib/shopify-cli/monorail.rb:37:in `send_events'
	 3: from /Users/chris/.shopify-app-cli/lib/shopify-cli/monorail.rb:37:in `select!'
	 2: from /Users/chris/.shopify-app-cli/lib/shopify-cli/monorail.rb:38:in `block in send_events'
	 1: from /Users/chris/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/json/common.rb:156:in `parse'
/Users/chris/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/json/common.rb:156:in `parse': 765: unexpected token at '{"schema_id":"app_cli_command/1.0","payload":{"cli_sha":"13c9669e8d4446b30062975d31b7e12b19c5eba0","uname":"Darwin Chriss-MacBook-Pro.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64\n","args":"help","timestamp":"2019-11-30T02:09:43.134610Z"}}' (JSON::ParserError)
```

I was able to work around this by just shorting the `send_events` function in monorail.rb (I just put "return" at the top of the function).

## Steps to reproduce the problem

Just type shopify into the terminal.

## Specifications

- App type: Next/Koa
- Operating System: Mac Mojave
- Shell: zsh, iterm
- Ruby version (ruby -v): 2.5.1

**Comment by tanema** [comment]
Thanks for reporting this, we should have a fix for that soon sorry about any inconvenience.

**Comment by katiedavis** [comment]
I'm going to close this as I believe it was fixed @chris-geelhoed please let me know if you're still having issues.
