### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by richardpenner** [Shopify/shopify-app-cli#416]
# Issue summary

Write a short description of the issue here ↓
I attempted to login but chose the wrong email address. The web page said "Authentication successful, this window will close shortly." But it didn't, and the terminal was showing a stack trace. Future attempts to create a project now fail authentication without prompting the web login, and the same stack trace is shown.

## Expected behavior

What do you think should happen?
I should be able to re-enter correct authentication info

## Actual behavior

What actually happens?
Not able to authenticate
Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

Initial auth attempt (web UI was shown):
```
Richards-MacBook-Pro:Downloads richardpenner$ shopify create project cli-channel
? Would you like to enable auto updates for Shopify App CLI? (You chose: yes)
Updating shopify-cli...done!                                                                                                                                    
? What type of app project would you like to create? (You chose: node embedded app)
✗ error: Your account was not found. Please sign up at https://partners.shopify.com/signup                                                                      
This command ran with ID: 96910                                                                                                                                 
Please include this information in any issues/report along with relevant logs
Traceback (most recent call last):
	29: from /Users/richardpenner/.shopify-app-cli/bin/shopify:36:in `<main>'
	28: from /Users/richardpenner/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	27: from /Users/richardpenner/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	26: from /Users/richardpenner/.shopify-app-cli/bin/shopify:37:in `block in <main>'
	25: from /Users/richardpenner/.shopify-app-cli/lib/shopify-cli/entry_point.rb:15:in `call'
	24: from /Users/richardpenner/.shopify-app-cli/lib/shopify-cli/monorail/log.rb:28:in `invocation'
	23: from /Users/richardpenner/.shopify-app-cli/lib/shopify-cli/monorail/log.rb:44:in `event'
	22: from /Users/richardpenner/.shopify-app-cli/lib/shopify-cli/entry_point.rb:16:in `block in call'
	21: from /Users/richardpenner/.shopify-app-cli/lib/shopify-cli/executor.rb:16:in `call'
	20: from /Users/richardpenner/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
	19: from /Users/richardpenner/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `with_traps'
	18: from /Users/richardpenner/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
	17: from /Users/richardpenner/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:46:in `block in with_traps'
	16: from /Users/richardpenner/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
	15: from /Users/richardpenner/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:47:in `block (2 levels) in with_traps'
	14: from /Users/richardpenner/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
	13: from /Users/richardpenner/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `with_logging'
	12: from /Users/richardpenner/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui.rb:143:in `log_output_to'
	11: from /Users/richardpenner/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:38:in `block in with_logging'
	10: from /Users/richardpenner/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:164:in `with_id'
	 9: from /Users/richardpenner/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:39:in `block (2 levels) in with_logging'
	 8: from /Users/richardpenner/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:17:in `block (2 levels) in call'
	 7: from /Users/richardpenner/.shopify-app-cli/lib/shopify-cli/command.rb:16:in `call'
	 6: from /Users/richardpenner/.shopify-app-cli/lib/shopify-cli/sub_command.rb:12:in `call'
	 5: from /Users/richardpenner/.shopify-app-cli/lib/shopify-cli/commands/create/project.rb:15:in `call'
	 4: from /Users/richardpenner/.shopify-app-cli/lib/shopify-cli/forms.rb:14:in `ask'
	 3: from /Users/richardpenner/.shopify-app-cli/lib/shopify-cli/forms/create_app.rb:13:in `ask'
	 2: from /Users/richardpenner/.shopify-app-cli/lib/shopify-cli/forms/create_app.rb:45:in `organization'
	 1: from /Users/richardpenner/.shopify-app-cli/lib/shopify-cli/forms/create_app.rb:37:in `organizations'
/Users/richardpenner/.shopify-app-cli/lib/shopify-cli/helpers/organizations.rb:7:in `fetch_all': undefined method `[]' for nil:NilClass (NoMethodError)
```
Subsequent attempts (web UI never shown):
```
Richards-MacBook-Pro:Downloads richardpenner$ shopify create project cli-channel
? What type of app project would you like to create? (You chose: node embedded app)
✗ error: Your account was not found. Please sign up at https://partners.shopify.com/signup                                                                      
This command ran with ID: 16957                                                                                                                                 
Please include this information in any issues/report along with relevant logs
Traceback (most recent call last):
	29: from /Users/richardpenner/.shopify-app-cli/bin/shopify:36:in `<main>'
	28: from /Users/richardpenner/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	27: from /Users/richardpenner/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	26: from /Users/richardpenner/.shopify-app-cli/bin/shopify:37:in `block in <main>'
	25: from /Users/richardpenner/.shopify-app-cli/lib/shopify-cli/entry_point.rb:15:in `call'
	24: from /Users/richardpenner/.shopify-app-cli/lib/shopify-cli/monorail/log.rb:28:in `invocation'
	23: from /Users/richardpenner/.shopify-app-cli/lib/shopify-cli/monorail/log.rb:44:in `event'
	22: from /Users/richardpenner/.shopify-app-cli/lib/shopify-cli/entry_point.rb:16:in `block in call'
	21: from /Users/richardpenner/.shopify-app-cli/lib/shopify-cli/executor.rb:16:in `call'
	20: from /Users/richardpenner/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
	19: from /Users/richardpenner/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `with_traps'
	18: from /Users/richardpenner/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
	17: from /Users/richardpenner/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:46:in `block in with_traps'
	16: from /Users/richardpenner/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
	15: from /Users/richardpenner/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:47:in `block (2 levels) in with_traps'
	14: from /Users/richardpenner/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
	13: from /Users/richardpenner/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `with_logging'
	12: from /Users/richardpenner/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui.rb:143:in `log_output_to'
	11: from /Users/richardpenner/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:38:in `block in with_logging'
	10: from /Users/richardpenner/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:164:in `with_id'
	 9: from /Users/richardpenner/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:39:in `block (2 levels) in with_logging'
	 8: from /Users/richardpenner/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:17:in `block (2 levels) in call'
	 7: from /Users/richardpenner/.shopify-app-cli/lib/shopify-cli/command.rb:16:in `call'
	 6: from /Users/richardpenner/.shopify-app-cli/lib/shopify-cli/sub_command.rb:12:in `call'
	 5: from /Users/richardpenner/.shopify-app-cli/lib/shopify-cli/commands/create/project.rb:15:in `call'
	 4: from /Users/richardpenner/.shopify-app-cli/lib/shopify-cli/forms.rb:14:in `ask'
	 3: from /Users/richardpenner/.shopify-app-cli/lib/shopify-cli/forms/create_app.rb:13:in `ask'
	 2: from /Users/richardpenner/.shopify-app-cli/lib/shopify-cli/forms/create_app.rb:45:in `organization'
	 1: from /Users/richardpenner/.shopify-app-cli/lib/shopify-cli/forms/create_app.rb:37:in `organizations'
/Users/richardpenner/.shopify-app-cli/lib/shopify-cli/helpers/organizations.rb:7:in `fetch_all': undefined method `[]' for nil:NilClass (NoMethodError)
```

## Steps to reproduce the problem

1.
1.
1.

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

## Specifications

- App type: node
- Operating System: macOS
- Shell: bash
- Ruby version (ruby -v): `ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]`

**Comment by richardpenner** [comment]
Note that I tried the `authenticate` command too:
```
Richards-MacBook-Pro:Downloads richardpenner$ shopify authenticate
✗ ✗ You are not in a Shopify app project
⭑ Run shopify create project to create your app
```

**Comment by richardpenner** [comment]
Might be related to https://github.com/Shopify/shopify-app-cli/issues/398

**Comment by tanema** [comment]
Yeah I have seen this with other members of shopify with multiple accounts. To clear all authentication, you can remove ~/.shopify-app-cli/.tmp/.db.pstore and then also definitely log out of all of your partners accounts. Then you can re-initiate authentication to restart the process.

**Comment by tanema** [comment]
@tylerball What do you think about clearing the current credentials when someone explicitly calls authenticate, and then when authentication is required at any other point it will just use the cached credentials

**Comment by richardpenner** [comment]
@tanema Thanks Tim – removing that file did the trick

**Comment by tylerball** [comment]
@tanema I think this is a great idea. Calling the `authenticate` command should clear everything.

**Comment by DuncanUszkay1** [comment]
>I think this is a great idea. Calling the authenticate command should clear everything.

I also think this is a great idea. Would be a much appreciated improvement

**Comment by ayronshopify** [comment]
You can now run `shopify logout` to clear any invalid credentials. You may need to run `shopify update` first to get this new version.

**Comment by richardpenner** [comment]
Excellent – thanks!

**Comment by aaronalbinson** [comment]
I continued to get this issue, my solution: I deleted the values in the .env file and the CLI asked the relevant questions again to get it to serve
