### ISSUE TITLE
`authenticate store` throws error

### ISSUE THREAD

**Issue by ErinRenNumber1** [Shopify/shopify-app-cli#418]
# Issue summary
When executing the command `shopify authenticate error`, it fails with NoMethodError.

Write a short description of the issue here ↓
See stack trace
MacBook-Pro-99:my_project erinren$ shopify authenticate store
This command ran with ID: 08748
Please include this information in any issues/report along with relevant logs

```
Traceback (most recent call last):
	25: from /Users/erinren/.shopify-app-cli/bin/shopify:36:in `<main>'
	24: from /Users/erinren/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	23: from /Users/erinren/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	22: from /Users/erinren/.shopify-app-cli/bin/shopify:37:in `block in <main>'
	21: from /Users/erinren/.shopify-app-cli/lib/shopify-cli/entry_point.rb:15:in `call'
	20: from /Users/erinren/.shopify-app-cli/lib/shopify-cli/monorail/log.rb:28:in `invocation'
	19: from /Users/erinren/.shopify-app-cli/lib/shopify-cli/monorail/log.rb:44:in `event'
	18: from /Users/erinren/.shopify-app-cli/lib/shopify-cli/entry_point.rb:16:in `block in call'
	17: from /Users/erinren/.shopify-app-cli/lib/shopify-cli/executor.rb:16:in `call'
	16: from /Users/erinren/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
	15: from /Users/erinren/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `with_traps'
	14: from /Users/erinren/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
	13: from /Users/erinren/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:46:in `block in with_traps'
	12: from /Users/erinren/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
	11: from /Users/erinren/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:47:in `block (2 levels) in with_traps'
	10: from /Users/erinren/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
	 9: from /Users/erinren/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `with_logging'
	 8: from /Users/erinren/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui.rb:143:in `log_output_to'
	 7: from /Users/erinren/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:38:in `block in with_logging'
	 6: from /Users/erinren/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:164:in `with_id'
	 5: from /Users/erinren/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:39:in `block (2 levels) in with_logging'
	 4: from /Users/erinren/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:17:in `block (2 levels) in call'
	 3: from /Users/erinren/.shopify-app-cli/lib/shopify-cli/command.rb:23:in `call'
	 2: from /Users/erinren/.shopify-app-cli/lib/shopify-cli/commands/authenticate.rb:10:in `call'
	 1: from /Users/erinren/.shopify-app-cli/lib/shopify-cli/task.rb:7:in `call'
/Users/erinren/.shopify-app-cli/lib/shopify-cli/tasks/ensure_loopback_url.rb:10:in `call': undefined method `[]' for nil:NilClass (NoMethodError)
```

## Specifications

- App type: node
- Operating System: MacOs
- Shell: bash
- Ruby version (ruby -v):ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin18]

**Comment by tanema** [comment]
please try again as this is what I get 
![image](https://user-images.githubusercontent.com/463193/70539177-4e58a080-1b31-11ea-9c9c-e8f2c5fa22cb.png)

**Comment by ErinRenNumber1** [comment]
Ah, right.  But shouldn't it just display a list of `help` command instead of the stack trace?

Also, why does the usage have the `shopify authenticate shop || identity` instead of just one `|`?
OK, I tried `shopify authenticate shop`, and I see this on my browser:
<img width="610" alt="Screen Shot 2019-12-10 at 9 47 30 AM" src="https://user-images.githubusercontent.com/39379964/70540110-a643d700-1b32-11ea-9914-1db8aaae14de.png">

Aside from that, I see the stack trace below.  I know we want to be verbose when error occurs, I just wanted to verify that all of this is intentional?  

```
⠦ Authetication with ren-dev-store.myshopify.com
#<Thread:0x00007faaf1875f70@/Users/erinren/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/spinner/spin_group.rb:43 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	8: from /Users/erinren/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/spinner/spin_group.rb:46:in `block in initialize'
	7: from /Users/erinren/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:120:in `run'
	6: from /Users/erinren/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:91:in `with_stdin_masked'
	5: from /Users/erinren/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:132:in `block in run'
	4: from /Users/erinren/.shopify-app-cli/lib/shopify-cli/commands/authenticate.rb:43:in `block in run_shop'
	3: from /Users/erinren/.shopify-app-cli/lib/shopify-cli/task.rb:7:in `call'
	2: from /Users/erinren/.shopify-app-cli/lib/shopify-cli/tasks/authenticate_shopify.rb:18:in `call'
	1: from /Users/erinren/.shopify-app-cli/lib/shopify-cli/oauth.rb:59:in `authenticate'
/Users/erinren/.shopify-app-cli/lib/shopify-cli/oauth.rb:113:in `receive_access_code': Timed out wh✗le waiting for response from shopify (ShopifyCli::OAuth::Error)
┏━━ Task Failed: Authetication with ren-dev-store.myshopify.com ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ ShopifyCli::OAuth::Error: Timed out while waiting for response from shopify
┃ 	from /Users/erinren/.shopify-app-cli/lib/shopify-cli/oauth.rb:113:in `receive_access_code'
┃ 	from /Users/erinren/.shopify-app-cli/lib/shopify-cli/oauth.rb:59:in `authenticate'
┃ 	from /Users/erinren/.shopify-app-cli/lib/shopify-cli/tasks/authenticate_shopify.rb:18:in `call'
┃ 	from /Users/erinren/.shopify-app-cli/lib/shopify-cli/task.rb:7:in `call'
┃ 	from /Users/erinren/.shopify-app-cli/lib/shopify-cli/commands/authenticate.rb:43:in `block in run_shop'
┃ 	from /Users/erinren/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:132:in `block in run'
┃ 	from /Users/erinren/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:91:in `with_stdin_masked'
┃ 	from /Users/erinren/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:120:in `run'
┃ 	from /Users/erinren/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/spinner/spin_group.rb:46:in `block in initialize'
┣━━ STDOUT ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ (empty)
┣━━ STDERR ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ (empty)
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (0.0s) ━━
#<Thread:0x00007faaf1857cc8@/Users/erinren/.shopify-app-cli/lib/shopify-cli/oauth.rb:89 aborting> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	1: from /Users/erinren/.shopify-app-cli/lib/shopify-cli/oauth.rb:105:in `block in listen_local'
/Users/erinren/.shopify-app-cli/lib/shopify-cli/oauth.rb:104:in `ensure in block in listen_local': undefined method `close_write' for nil:NilClass (NoMethodError)
```

**Comment by tanema** [comment]
> Ah, right. But shouldn't it just display a list of help command instead of the stack trace?

Yes as you can see in my screenshot
 
> Also, why does the usage have the shopify authenticate shop || identity instead of just one |?

Its an OR not a Pipe

> OK, I tried shopify authenticate shop, and I see this on my browser:

I am not sure what that error is, you might have to ask dev-accel

> Aside from that, I see the stack trace below. I know we want to be verbose when error occurs, I just wanted to verify that all of this is intentional?

Yes
