### ISSUE TITLE
shopify serve — Task Failed: Installing ngrok...

### ISSUE THREAD

**Issue by oneezy** [Shopify/shopify-app-cli#425]
# Issue summary
`shopify serve` isn't working properly

## Expected behavior
start local dev server

## Actual behavior
doesn't start local dev server
```
➜  APP_NAME shopify serve
/home/Justin/.shopify-app-cli/bin/support/load_shopify.rb:12: warning: Insecure world writable dir /home/Justin/.nvm/versions/node/v8.0.0 in PATH, mode 040777
✗ Installing ngrok...
┏━━ Task Failed: Installing ngrok... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ Errno::ENOENT: No such file or directory - unzip
┃       from /home/Justin/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/system.rb:114:in `spawn'
┃       from /home/Justin/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/system.rb:114:in `system'
┃       from /home/Justin/.shopify-app-cli/lib/shopify-cli/context/system.rb:11:in `system'
┃       from /home/Justin/.shopify-app-cli/lib/shopify-cli/tasks/tunnel.rb:81:in `block in install'
┃       from /home/Justin/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:132:in `block in run'
┃       from /home/Justin/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:91:in `with_stdin_masked'
┃       from /home/Justin/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:120:in `run'
┃       from /home/Justin/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/spinner/spin_group.rb:46:in `block in initialize'
┣━━ STDOUT ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ (empty)
┣━━ STDERR ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ (empty)
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (0.01s) ━━
x ngrok tunnel stopped
This command ran with ID: 47357
Please include this information in any issues/report along with relevant logs
/home/Justin/.shopify-app-cli/lib/shopify-cli/tasks/tunnel.rb:91:in `rescue in fetch_url': Unable to fetch external url (ShopifyCli::Tasks::Tunnel::FetchUrlError)
        from /home/Justin/.shopify-app-cli/lib/shopify-cli/tasks/tunnel.rb:88:in `fetch_url'
        from /home/Justin/.shopify-app-cli/lib/shopify-cli/tasks/tunnel.rb:51:in `start'
        from /home/Justin/.shopify-app-cli/lib/shopify-cli/tasks/tunnel.rb:22:in `call'
        from /home/Justin/.shopify-app-cli/lib/shopify-cli/task.rb:7:in `call'
        from /home/Justin/.shopify-app-cli/lib/shopify-cli/commands/serve.rb:18:in `call'
        from /home/Justin/.shopify-app-cli/lib/shopify-cli/command.rb:23:in `call'
        from /home/Justin/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:17:in `block (2 levels) in call'
        from /home/Justin/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:39:in `block (2 levels) in with_logging'
        from /home/Justin/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:164:in `with_id'
        from /home/Justin/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:38:in `block in with_logging'
        from /home/Justin/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui.rb:143:in `log_output_to'
        from /home/Justin/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `with_logging'
        from /home/Justin/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
        from /home/Justin/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:47:in `block (2 levels) in with_traps'
        from /home/Justin/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:53:in `twrap'
        from /home/Justin/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:46:in `block in with_traps'
        from /home/Justin/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
        from /home/Justin/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `with_traps'
        from /home/Justin/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        from /home/Justin/.shopify-app-cli/lib/shopify-cli/executor.rb:16:in `call'
        from /home/Justin/.shopify-app-cli/lib/shopify-cli/entry_point.rb:16:in `block in call'
        from /home/Justin/.shopify-app-cli/lib/shopify-cli/monorail/log.rb:44:in `event'
        from /home/Justin/.shopify-app-cli/lib/shopify-cli/monorail/log.rb:28:in `invocation'
        from /home/Justin/.shopify-app-cli/lib/shopify-cli/entry_point.rb:15:in `call'
        from /home/Justin/.shopify-app-cli/bin/shopify:37:in `block in <main>'
        from /home/Justin/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        from /home/Justin/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        from /home/Justin/.shopify-app-cli/bin/shopify:36:in `<main>'
➜  APP_NAME                                                                           
```

## Specifications
- App type: `Shopify`
- Operating System: `Windows 10`
- Shell: `GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)`
- Ruby version (ruby -v): `ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]`
- Node version: `v8.0.0`
- NPM version: `v5.8.0`

**Comment by oneezy** [comment]
After installing `unzip`, I was able to get passed this step
```
sudo apt-get install unzip
```
hopefully this can help someone else

**Comment by tylerball** [comment]
@oneezy Thanks for the report, we should print an error if we don't find `unzip` and show that instruction.
