### ISSUE TITLE
shopify serve — SyntaxError: Unexpected token ... (Failed to complete tunnel connection)

### ISSUE THREAD

**Issue by oneezy** [Shopify/shopify-app-cli#426]
# Issue summary
`shopify serve` won't start up the server

## Expected behavior
startup server

## Actual behavior
I get the error log below and when I visit the ngrok tunnel it says "Failed to complete tunnel connection"
```
➜  APP_TEST shopify serve
/home/Justin/.shopify-app-cli/bin/support/load_shopify.rb:12: warning: Insecure world writable dir /home/Justin/.local in PATH, mode 040777
✓ ngrok tunnel running at https://758ba86d.ngrok.io
✓ .env saved to project root
✓ Whitelist URLS updated in Partners Dashboard
┏━━ Running server... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┃
┃ > shopify-node-app@1.0.0 dev /mnt/c/Users/Work/Desktop/www/shopify/cli-test/APP_TEST
┃ > NODE_ENV=development nodemon ./server/index.js --watch ./server/index.js
┃
┃ /mnt/c/Users/Work/Desktop/www/shopify/cli-test/APP_TEST/node_modules/nodemon/node_modules/chokidar/index.js:904
┃   const options = {type: EV_ALL, alwaysStat: true, lstat: true, ...opts};
┃                                                                 ^^^
┃
┃ SyntaxError: Unexpected token ...
┃     at createScript (vm.js:74:10)
┃     at Object.runInThisContext (vm.js:116:10)
┃     at Module._compile (module.js:533:28)
┃     at Object.Module._extensions..js (module.js:580:10)
┃     at Module.load (module.js:503:32)
┃     at tryModuleLoad (module.js:466:12)
┃     at Function.Module._load (module.js:458:3)
┃     at Module.require (module.js:513:17)
┃     at require (internal/module.js:11:18)
┃     at Object.<anonymous> (/mnt/c/Users/Work/Desktop/www/shopify/cli-test/APP_TEST/node_modules/nodemon/lib/monitor/watch.js:6:16)
┃ npm ERR! code ELIFECYCLE
┃ npm ERR! errno 1
┃ npm ERR! shopify-node-app@1.0.0 dev: `NODE_ENV=development nodemon ./server/index.js --watch ./server/index.js`
┃ npm ERR! Exit status 1
┃ npm ERR!
┃ npm ERR! Failed at the shopify-node-app@1.0.0 dev script.
┃ npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
┃
┃ npm ERR! A complete log of this run can be found in:
┃ npm ERR!     /home/Justin/.npm/_logs/2019-12-15T13_32_08_902Z-debug.log
```

## Specifications
- App type: `Public`
- Operating System: `Windows 10`
- Shell: `GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)`
- Ruby version (ruby -v): `ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]`
- Node version: `v8.0.0`
- NPM version: `v5.8.0`

![image](https://user-images.githubusercontent.com/7369575/70863473-38baf080-1f0e-11ea-8b3a-da600608bd00.png)

**Comment by oneezy** [comment]
After updating **Node** to `v12.13.1` and re-trying `shopify serve`, followed by the instructions given in issue #201 , I'm finally able to view my app from the ngrok url, however,,, I get a `fetchError` when it tries compiling... Any ideas?

```
➜  APP_TEST node --version
v12.13.1
➜  APP_TEST shopify serve
/home/Justin/.shopify-app-cli/bin/support/load_shopify.rb:12: warning: Insecure world writable dir /home/Justin/.nvm/versions/node/v12.13.1 in PATH, mode 040777
✓ ngrok tunnel running at https://758ba86d.ngrok.io
✓ .env saved to project root                                           ✓ Whitelist URLS updated in Partners Dashboard
┏━━ Running server... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃
┃ > shopify-node-app@1.0.0 dev /mnt/c/Users/Work/Desktop/www/shopify/cli-test/APP_TEST
┃ > NODE_ENV=development nodemon ./server/index.js --watch ./server/index.js
┃
┃ [nodemon] 2.0.2
┃ [nodemon] to restart at any time, enter `rs`
┃ [nodemon] watching dir(s): server/index.js
┃ [nodemon] watching extensions: js,mjs,json
┃ [nodemon] starting `node ./server/index.js`
┃ > Ready on http://localhost:8081
┃ [ event ] build page: /
┃ [ wait ]  compiling ...
┃
┃   FetchError: request to https://the-spirit-army.myshopify.com/admin/metafields.json failed, reason: Client network socket disconnected before secure TLS connection was established
┃       at ClientRequest.<anonymous> (/mnt/c/Users/Work/Desktop/www/shopify/cli-test/APP_TEST/node_modules/isomorphic-fetch/node_modules/node-fetch/index.js:133:11)
┃       at ClientRequest.emit (events.js:210:5)
┃       at TLSSocket.socketErrorListener (_http_client.js:406:9)
┃       at TLSSocket.emit (events.js:210:5)
┃       at emitErrorNT (internal/streams/destroy.js:92:8)
┃       at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
┃       at processTicksAndRejections (internal/process/task_queues.js:80:21)
┃
┃
┃   FetchError: request to https://the-spirit-army.myshopify.com/admin/metafields.json failed, reason: Client network socket disconnected before secure TLS connection was established
┃       at ClientRequest.<anonymous> (/mnt/c/Users/Work/Desktop/www/shopify/cli-test/APP_TEST/node_modules/isomorphic-fetch/node_modules/node-fetch/index.js:133:11)
┃       at ClientRequest.emit (events.js:210:5)
┃       at TLSSocket.socketErrorListener (_http_client.js:406:9)
┃       at TLSSocket.emit (events.js:210:5)
┃       at emitErrorNT (internal/streams/destroy.js:92:8)
┃       at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
┃       at processTicksAndRejections (internal/process/task_queues.js:80:21)
┃
┃
┃   FetchError: request to https://the-spirit-army.myshopify.com/admin/metafields.json failed, reason: Client network socket disconnected before secure TLS connection was established
┃       at ClientRequest.<anonymous> (/mnt/c/Users/Work/Desktop/www/shopify/cli-test/APP_TEST/node_modules/isomorphic-fetch/node_modules/node-fetch/index.js:133:11)
┃       at ClientRequest.emit (events.js:210:5)
┃       at TLSSocket.socketErrorListener (_http_client.js:406:9)
┃       at TLSSocket.emit (events.js:210:5)
┃       at emitErrorNT (internal/streams/destroy.js:92:8)
┃       at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
┃       at processTicksAndRejections (internal/process/task_queues.js:80:21)
┃
┃ [ event ] disposing inactive page(s): /
┃ [ event ] client pings, but there's no entry for page: /
┃ [ event ] build page: /
┃ [ wait ]  compiling ...
```

**Comment by katiedavis** [comment]
@oneezy do you get these errors when you try to run an empty app? or only when you add the metafields request?

**Comment by Freelancer740** [comment]
Hey,
![Screenshot_2](https://user-images.githubusercontent.com/46267202/137604711-f7fbc986-137d-4cd0-b88d-33632e052e9f.png)
 I have v14.18.0 of node but still, I'm getting this error
