### ISSUE TITLE
Authorization URL does not respond

### ISSUE THREAD

**Issue by ioapps-dev** [Shopify/shopify-app-cli#432]
Basically the authorization url does not respond:
https://accounts.shopify.com/oauth/authorize?..

Then a timeout error occurs:
```
younes@DESKTOP-F75LROO:~$ shopify create project shopify-test-1
/home/younes/.shopify-app-cli/bin/support/load_shopify.rb:12: warning: Insecure world writable dir /home/younes/.shopify-app-cli/bin in PATH, mode 040777
? What type of app project would you like to create? (You chose: node embedded app)
Please open https://accounts.shopify.com/oauth/authorize?client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&scope=openid+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.app.cli.access&redirect_uri=http%3A%2F%2Fapp-cli-loopback.shopifyapps.com%3A3456&state=1cbc526e22d8954310ef7d25b2b23216f004b7a7481a6137f91edd21fd42&response_type=code&code_challenge=JESOZEYcJ6SOySPitLBiC5RBOBUhkG8Qhdjbob6DnIM&code_challenge_method=S256 in your browser
This command ran with ID: 28373
Please include this information in any issues/report along with relevant logs
#<Thread:0x00007fffcc13a460@/home/younes/.shopify-app-cli/lib/shopify-cli/oauth.rb:89 aborting> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        1: from /home/younes/.shopify-app-cli/lib/shopify-cli/oauth.rb:105:in `block in listen_local'
/home/younes/.shopify-app-cli/lib/shopify-cli/oauth.rb:104:in `ensure in block in listen_local': undefined method `close_write' for nil:NilClass (NoMethodError)
Traceback (most recent call last):
        40: from /home/younes/.shopify-app-cli/bin/shopify:36:in `<main>'
        39: from /home/younes/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        38: from /home/younes/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        37: from /home/younes/.shopify-app-cli/bin/shopify:37:in `block in <main>'
        36: from /home/younes/.shopify-app-cli/lib/shopify-cli/entry_point.rb:15:in `call'
        35: from /home/younes/.shopify-app-cli/lib/shopify-cli/monorail/log.rb:28:in `invocation'
        34: from /home/younes/.shopify-app-cli/lib/shopify-cli/monorail/log.rb:44:in `event'
        33: from /home/younes/.shopify-app-cli/lib/shopify-cli/entry_point.rb:16:in `block in call'
        32: from /home/younes/.shopify-app-cli/lib/shopify-cli/executor.rb:16:in `call'
        31: from /home/younes/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        30: from /home/younes/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `with_traps'
        29: from /home/younes/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
        28: from /home/younes/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:46:in `block in with_traps'
        27: from /home/younes/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:53:in `twrap'
        26: from /home/younes/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:47:in `block (2 levels) in with_traps'
        25: from /home/younes/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
        24: from /home/younes/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `with_logging'
        23: from /home/younes/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui.rb:143:in `log_output_to'
        22: from /home/younes/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:38:in `block in with_logging'
        21: from /home/younes/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:164:in `with_id'
        20: from /home/younes/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:39:in `block (2 levels) in with_logging'
        19: from /home/younes/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:17:in `block (2 levels) in call'
        18: from /home/younes/.shopify-app-cli/lib/shopify-cli/command.rb:16:in `call'
        17: from /home/younes/.shopify-app-cli/lib/shopify-cli/sub_command.rb:12:in `call'
        16: from /home/younes/.shopify-app-cli/lib/shopify-cli/commands/create/project.rb:15:in `call'
        15: from /home/younes/.shopify-app-cli/lib/shopify-cli/forms.rb:14:in `ask'
        14: from /home/younes/.shopify-app-cli/lib/shopify-cli/forms/create_app.rb:13:in `ask'
        13: from /home/younes/.shopify-app-cli/lib/shopify-cli/forms/create_app.rb:45:in `organization'
        12: from /home/younes/.shopify-app-cli/lib/shopify-cli/forms/create_app.rb:37:in `organizations'
        11: from /home/younes/.shopify-app-cli/lib/shopify-cli/helpers/organizations.rb:6:in `fetch_all'
        10: from /home/younes/.shopify-app-cli/lib/shopify-cli/helpers/partners_api.rb:34:in `query'
         9: from /home/younes/.shopify-app-cli/lib/shopify-cli/helpers/partners_api.rb:42:in `authenticated_req'
         8: from /home/younes/.shopify-app-cli/lib/shopify-cli/helpers/partners_api.rb:35:in `block in query'
         7: from /home/younes/.shopify-app-cli/lib/shopify-cli/helpers/partners_api.rb:53:in `api_client'
         6: from /home/younes/.shopify-app-cli/lib/shopify-cli/helpers/pkce_token.rb:6:in `read'
         5: from /home/younes/.shopify-app-cli/lib/shopify-cli/helpers/store.rb:37:in `get'
         4: from /home/younes/.shopify-app-cli/lib/shopify-cli/helpers/pkce_token.rb:7:in `block in read'
         3: from /home/younes/.shopify-app-cli/lib/shopify-cli/task.rb:7:in `call'
         2: from /home/younes/.shopify-app-cli/lib/shopify-cli/tasks/authenticate_identity.rb:15:in `call'
         1: from /home/younes/.shopify-app-cli/lib/shopify-cli/oauth.rb:59:in `authenticate'
/home/younes/.shopify-app-cli/lib/shopify-cli/oauth.rb:113:in `receive_access_code': Timed out while waiting for response from shopify (ShopifyCli::OAuth::Error)
```

**Comment by tanema** [comment]
What happens when you open that link?

**Comment by ioapps-dev** [comment]
Authentication step does not work:
Please open **https://accounts.shopify.com/oauth/authorize?client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&scope=openid+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.app.cli.access&redirect_uri=http%3A%2F%2Fapp-cli-loopback.shopifyapps.com%3A3456&state=1cbc526e22d8954310ef7d25b2b23216f004b7a7481a6137f91edd21fd42&response_type=code&code_challenge=JESOZEYcJ6SOySPitLBiC5RBOBUhkG8Qhdjbob6DnIM&code_challenge_method=S256** in your browser

**Comment by tanema** [comment]
Do you copy and paste that URL into your browser?

**Comment by ioapps-dev** [comment]
Of course but it does not respond, it is as if the domain did not exist.

**Comment by tanema** [comment]
Do you get a DNS error, a 404, a 500. How does it respond.

**Comment by ioapps-dev** [comment]
The browser does not return anything, I think they can easily reproduce the error.

**Comment by tanema** [comment]
When I click that link that you posted, I get a successful authentication and then a response that says `http://app-cli-loopback.shopifyapps.com/` cannot be reached and that is because I didn't run the cli to start the local server. 

- Is this what you are getting. (I dont think so since the error you posted was actually the local server timing out waiting for a response)
- What is the response from shopify. Open your browsers console and find the response status code of the page loading. Also, if there are any errors in the console show them to me. Also if there is any HTML rendered show it to me. If there is literally any thing else show it to me. All you have given me is that it doesnt work and I have a hard time debugging that.
- Also you did not fill out our issue template which helps us greatly please provide to me 
    - App type Rails or Node
    - Operating System
    - Shell Type and Version
    - Ruby version

**Comment by emiliobool** [comment]
In my case it was that I was running the commands via ssh on a local server, so I had to also manually curl the app-cli-loopback.shopifyapps.com link from the same server

I wouldn't be surprised if a lot of people running WSL2, a virtual machine or similar end up having the same issue.

**Comment by tanema** [comment]
@emiliobool I have tested this on windows, but it seems like you have more experience with it so maybe you can help clarify. If you run a webserver on localhost in WSL, does it not bind to the host localhost? Is the WSL assigned an IP instead like a proper virtual machine?

**Comment by emiliobool** [comment]
I'm not that experienced with WSL but as far as I know the old one does
bind to the same interface, but the new one (WSL2) has its own network
stack like a regular virtual machine. Im not sure if they have or will
change that behavior as the last time I tried it was a few months ago.

**Comment by khanhquocnguyen** [comment]
> In my case it was that I was running the commands via ssh on a local server, so I had to also manually curl the app-cli-loopback.shopifyapps.com link from the same server
> 
> I wouldn't be surprised if a lot of people running WSL2, a virtual machine or similar end up having the same issue.

I got the same issue. I'm developing my app in cloud machine with console interface, so I don't know how to open the authorization url in console.

**Comment by tanema** [comment]
Currently, we can only support a local process. We have no way to complete the OAuth process currently using a remote host. I will have to think about it for a while on how to allow that but if we were able to allow it, you would need an addressable host.

**Comment by andrewwise** [comment]
I'm getting the same issue on a fresh install of Ubuntu 19.10.

Running `shopify serve` on an existing rails project that works on another machine and `shopify create project test` with either a rails or node project both give the oauth URL which when followed in browser redirects to something like `http://app-cli-loopback.shopifyapps.com:3456/?code=XXX&state=XXX`. This gives a DNS error on both Chromium and Firefox.

Have I missed installing something I wonder?

After a short while of waiting it just times out:

```
This command ran with ID: 00982
Please include this information in any issues/report along with relevant logs
#<Thread:0x00005618c9e8c910@/home/andrew/.shopify-app-cli/lib/shopify-cli/oauth.rb:89 aborting> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	1: from /home/andrew/.shopify-app-cli/lib/shopify-cli/oauth.rb:105:in `block in listen_local'
/home/andrew/.shopify-app-cli/lib/shopify-cli/oauth.rb:104:in `ensure in block in listen_local': undefined method `close_write' for nil:NilClass (NoMethodError)
Traceback (most recent call last):
	40: from /home/andrew/.shopify-app-cli/bin/shopify:36:in `<main>'
	39: from /home/andrew/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	38: from /home/andrew/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	37: from /home/andrew/.shopify-app-cli/bin/shopify:37:in `block in <main>'
	36: from /home/andrew/.shopify-app-cli/lib/shopify-cli/entry_point.rb:15:in `call'
	35: from /home/andrew/.shopify-app-cli/lib/shopify-cli/monorail/log.rb:28:in `invocation'
	34: from /home/andrew/.shopify-app-cli/lib/shopify-cli/monorail/log.rb:44:in `event'
	33: from /home/andrew/.shopify-app-cli/lib/shopify-cli/entry_point.rb:16:in `block in call'
	32: from /home/andrew/.shopify-app-cli/lib/shopify-cli/executor.rb:16:in `call'
	31: from /home/andrew/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
	30: from /home/andrew/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `with_traps'
	29: from /home/andrew/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
	28: from /home/andrew/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:46:in `block in with_traps'
	27: from /home/andrew/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:53:in `twrap'
	26: from /home/andrew/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:47:in `block (2 levels) in with_traps'
	25: from /home/andrew/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
	24: from /home/andrew/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `with_logging'
	23: from /home/andrew/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui.rb:143:in `log_output_to'
	22: from /home/andrew/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:38:in `block in with_logging'
	21: from /home/andrew/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:164:in `with_id'
	20: from /home/andrew/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:39:in `block (2 levels) in with_logging'
	19: from /home/andrew/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:17:in `block (2 levels) in call'
	18: from /home/andrew/.shopify-app-cli/lib/shopify-cli/command.rb:16:in `call'
	17: from /home/andrew/.shopify-app-cli/lib/shopify-cli/sub_command.rb:12:in `call'
	16: from /home/andrew/.shopify-app-cli/lib/shopify-cli/commands/create/project.rb:15:in `call'
	15: from /home/andrew/.shopify-app-cli/lib/shopify-cli/forms.rb:14:in `ask'
	14: from /home/andrew/.shopify-app-cli/lib/shopify-cli/forms/create_app.rb:13:in `ask'
	13: from /home/andrew/.shopify-app-cli/lib/shopify-cli/forms/create_app.rb:45:in `organization'
	12: from /home/andrew/.shopify-app-cli/lib/shopify-cli/forms/create_app.rb:37:in `organizations'
	11: from /home/andrew/.shopify-app-cli/lib/shopify-cli/helpers/organizations.rb:6:in `fetch_all'
	10: from /home/andrew/.shopify-app-cli/lib/shopify-cli/helpers/partners_api.rb:34:in `query'
	 9: from /home/andrew/.shopify-app-cli/lib/shopify-cli/helpers/partners_api.rb:42:in `authenticated_req'
	 8: from /home/andrew/.shopify-app-cli/lib/shopify-cli/helpers/partners_api.rb:35:in `block in query'
	 7: from /home/andrew/.shopify-app-cli/lib/shopify-cli/helpers/partners_api.rb:53:in `api_client'
	 6: from /home/andrew/.shopify-app-cli/lib/shopify-cli/helpers/pkce_token.rb:6:in `read'
	 5: from /home/andrew/.shopify-app-cli/lib/shopify-cli/helpers/store.rb:37:in `get'
	 4: from /home/andrew/.shopify-app-cli/lib/shopify-cli/helpers/pkce_token.rb:7:in `block in read'
	 3: from /home/andrew/.shopify-app-cli/lib/shopify-cli/task.rb:7:in `call'
	 2: from /home/andrew/.shopify-app-cli/lib/shopify-cli/tasks/authenticate_identity.rb:15:in `call'
	 1: from /home/andrew/.shopify-app-cli/lib/shopify-cli/oauth.rb:59:in `authenticate'
/home/andrew/.shopify-app-cli/lib/shopify-cli/oauth.rb:113:in `receive_access_code': Timed out while waiting for response from shopify (ShopifyCli::OAuth::Error)
```

**Comment by tanema** [comment]
What is your DNS error? That domain is setup to resolve to your localhost.

**Comment by andrewwise** [comment]
Thanks for the reply @tanema!

I just get the standard browser can't find this domain error:

```
This site can’t be reached
app-cli-loopback.shopifyapps.com’s server IP address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN
```

**Comment by andrewwise** [comment]
Not sure why I didn't try this before but using: `localhost` instead of `app-cli-loopback.shopifyapps.com` works.

e.g. `http://localhost:3456/?code=XXX&state=XXX`

**Comment by cstehreem** [comment]
@andrewwise I am also getting the same error suddenly. I was working fine on my application previously. But I am not seeing any code in the given url, can you tell me how to extract that? Seems like it is expecting code in response. Here is my link:

`https://accounts.shopify.com/oauth/authorize?client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&scope=openid+https://api.shopify.com/auth/partners.app.cli.access&redirect_uri=http://app-cli-loopback.shopifyapps.com:3456&state=701373a7afddf809a703b462fb77eb68551faa9c37ea3d7971d1c3140728&response_type=code&code_challenge=lbszlcetzgLKutnEeIL_Yo3VornlrHzogY0EcdUXmnc&code_challenge_method=S256`

**Comment by ljle** [comment]
As @emiliobool pointed out, WSL2 users will have trouble with authentication because you're not opening the authentication URL from within the Linux distro you're using, you're opening it from Windows instead. I struggled with this for a while but found a solution in case anyone else has the same problem:

1. Go to this article https://nickymeuleman.netlify.app/blog/gui-on-wsl2-cypress and follow the instructions to setup the X server program on Windows (ignore the Cypress part).
2. Install any browser on your WSL2 distro and run it, it'll open in a new window from the program you just installed on Windows.
3. Run `shopify create` and open the authentication URL in the distro's browser.
