### ISSUE TITLE
Switching partner accounts causes unhelpful error in CLI

### ISSUE THREAD

**Issue by MitchDickinson** [Shopify/shopify-app-cli#463]
# Issue summary

If you log in to another partner account while operating the shopify app CLI, you get unhelpful errors when issuing commands.

## Steps to reproduce the problem
1. Create a new app with the app CLI
2. Once it's created, but before `serve`, logout of the partner dashboard and login as a different organization.
3. Try issuing the `shopify serve` command. 
4. Error below happens.

## Expected behavior

It should give me an error telling me that I no longer have appropriate permission to that app and prompt me to log back into the correct partner account.

## Actual behavior

Note this happens during `serve`.  I did not test other commands but I assume similar problems will happen.

```
Traceback (most recent call last):
	27: from /Users/mitchdickinson/.shopify-app-cli/bin/shopify:36:in `<main>'
	26: from /Users/mitchdickinson/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	25: from /Users/mitchdickinson/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	24: from /Users/mitchdickinson/.shopify-app-cli/bin/shopify:37:in `block in <main>'
	23: from /Users/mitchdickinson/.shopify-app-cli/lib/shopify-cli/entry_point.rb:15:in `call'
	22: from /Users/mitchdickinson/.shopify-app-cli/lib/shopify-cli/monorail/log.rb:28:in `invocation'
	21: from /Users/mitchdickinson/.shopify-app-cli/lib/shopify-cli/monorail/log.rb:44:in `event'
	20: from /Users/mitchdickinson/.shopify-app-cli/lib/shopify-cli/entry_point.rb:16:in `block in call'
	19: from /Users/mitchdickinson/.shopify-app-cli/lib/shopify-cli/executor.rb:16:in `call'
	18: from /Users/mitchdickinson/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
	17: from /Users/mitchdickinson/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `with_traps'
	16: from /Users/mitchdickinson/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
	15: from /Users/mitchdickinson/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:46:in `block in with_traps'
	14: from /Users/mitchdickinson/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
	13: from /Users/mitchdickinson/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:47:in `block (2 levels) in with_traps'
	12: from /Users/mitchdickinson/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
	11: from /Users/mitchdickinson/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `with_logging'
	10: from /Users/mitchdickinson/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui.rb:143:in `log_output_to'
	 9: from /Users/mitchdickinson/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:38:in `block in with_logging'
	 8: from /Users/mitchdickinson/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:164:in `with_id'
	 7: from /Users/mitchdickinson/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:39:in `block (2 levels) in with_logging'
	 6: from /Users/mitchdickinson/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:17:in `block (2 levels) in call'
	 5: from /Users/mitchdickinson/.shopify-app-cli/lib/shopify-cli/command.rb:23:in `call'
	 4: from /Users/mitchdickinson/.shopify-app-cli/lib/shopify-cli/app_type_command.rb:26:in `call'
	 3: from /Users/mitchdickinson/.shopify-app-cli/lib/shopify-cli/commands/serve/rails.rb:8:in `call'
	 2: from /Users/mitchdickinson/.shopify-app-cli/lib/shopify-cli/commands/serve.rb:23:in `setup'
	 1: from /Users/mitchdickinson/.shopify-app-cli/lib/shopify-cli/task.rb:7:in `call'
/Users/mitchdickinson/.shopify-app-cli/lib/shopify-cli/tasks/update_dashboard_urls.rb:14:in `call': undefined method `[]' for nil:NilClass (NoMethodError)
```

## Specifications

- App type: Rails
- Operating System: OSX 10.15.3
- Shell: iTerm2
- Ruby version (ruby -v): 2.6.3

**Comment by ErinRenNumber1** [comment]
@katiedavis: do you think the work around would be:
to remove ~/.shopify-app-cli/.tmp/.db.pstore and then also log out of all partners accounts.

**Comment by katiedavis** [comment]
@ErinRenNumber1 yep! I believe it's mostly the store, not logging out of accounts, but it never hurts to log out.
We are tracking this issue here: 
https://github.com/Shopify/shopify-app-cli/issues/416

**Comment by ayronshopify** [comment]
You can now run `shopify logout` to clear any invalid credentials. You may need to run `shopify update` first to get this new version.
