### ISSUE TITLE
Timeouts during OAuth process

### ISSUE THREAD

**Issue by DuncanUszkay1** [Shopify/shopify-app-cli#469]
# Issue summary

I find that I often get OAuth timeouts when authenticating if the login takes any longer than normal, for instance if I mistype my password the first time or need to go get an authenticator code. When that happens, I get an oauth timeout:
```
36: from /Users/duncanuszkay/src/github.com/Shopify/temp-shopify-app-cli/bin/shopify:36:in `<main>'
	35: from /Users/duncanuszkay/src/github.com/Shopify/temp-shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	34: from /Users/duncanuszkay/src/github.com/Shopify/temp-shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	33: from /Users/duncanuszkay/src/github.com/Shopify/temp-shopify-app-cli/bin/shopify:37:in `block in <main>'
	32: from /Users/duncanuszkay/src/github.com/Shopify/temp-shopify-app-cli/lib/shopify-cli/entry_point.rb:20:in `call'
	31: from /Users/duncanuszkay/src/github.com/Shopify/temp-shopify-app-cli/lib/shopify-cli/monorail/log.rb:28:in `invocation'
	30: from /Users/duncanuszkay/src/github.com/Shopify/temp-shopify-app-cli/lib/shopify-cli/monorail/log.rb:44:in `event'
	29: from /Users/duncanuszkay/src/github.com/Shopify/temp-shopify-app-cli/lib/shopify-cli/entry_point.rb:21:in `block in call'
	28: from /Users/duncanuszkay/src/github.com/Shopify/temp-shopify-app-cli/lib/shopify-cli/executor.rb:16:in `call'
	27: from /Users/duncanuszkay/src/github.com/Shopify/temp-shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
	26: from /Users/duncanuszkay/src/github.com/Shopify/temp-shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `with_traps'
	25: from /Users/duncanuszkay/src/github.com/Shopify/temp-shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
	24: from /Users/duncanuszkay/src/github.com/Shopify/temp-shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:46:in `block in with_traps'
	23: from /Users/duncanuszkay/src/github.com/Shopify/temp-shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
	22: from /Users/duncanuszkay/src/github.com/Shopify/temp-shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:47:in `block (2 levels) in with_traps'
	21: from /Users/duncanuszkay/src/github.com/Shopify/temp-shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
	20: from /Users/duncanuszkay/src/github.com/Shopify/temp-shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `with_logging'
	19: from /Users/duncanuszkay/src/github.com/Shopify/temp-shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui.rb:143:in `log_output_to'
	18: from /Users/duncanuszkay/src/github.com/Shopify/temp-shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:38:in `block in with_logging'
	17: from /Users/duncanuszkay/src/github.com/Shopify/temp-shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:164:in `with_id'
	16: from /Users/duncanuszkay/src/github.com/Shopify/temp-shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:39:in `block (2 levels) in with_logging'
	15: from /Users/duncanuszkay/src/github.com/Shopify/temp-shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:17:in `block (2 levels) in call'
	14: from /Users/duncanuszkay/src/github.com/Shopify/temp-shopify-app-cli/lib/shopify-cli/command.rb:16:in `call'
	13: from /Users/duncanuszkay/src/github.com/Shopify/temp-shopify-app-cli/lib/shopify-cli/sub_command.rb:12:in `call'
	12: from /Users/duncanuszkay/src/github.com/Shopify/temp-shopify-app-cli/lib/shopify-cli/commands/create/app.rb:15:in `call'
	11: from /Users/duncanuszkay/src/github.com/Shopify/temp-shopify-app-cli/lib/shopify-cli/forms.rb:17:in `ask'
	10: from /Users/duncanuszkay/src/github.com/Shopify/temp-shopify-app-cli/lib/shopify-cli/forms/create_app.rb:13:in `ask'
	 9: from /Users/duncanuszkay/src/github.com/Shopify/temp-shopify-app-cli/lib/shopify-cli/forms/create_app.rb:46:in `organization'
	 8: from /Users/duncanuszkay/src/github.com/Shopify/temp-shopify-app-cli/lib/shopify-cli/forms/create_app.rb:37:in `organizations'
	 7: from /Users/duncanuszkay/src/github.com/Shopify/temp-shopify-app-cli/lib/shopify-cli/helpers/organizations.rb:6:in `fetch_all'
	 6: from /Users/duncanuszkay/src/github.com/Shopify/temp-shopify-app-cli/lib/shopify-cli/helpers/partners_api.rb:34:in `query'
	 5: from /Users/duncanuszkay/src/github.com/Shopify/temp-shopify-app-cli/lib/shopify-cli/helpers/partners_api.rb:45:in `authenticated_req'
	 4: from /Users/duncanuszkay/src/github.com/Shopify/temp-shopify-app-cli/lib/shopify-cli/helpers/partners_api.rb:48:in `rescue in authenticated_req'
	 3: from /Users/duncanuszkay/src/github.com/Shopify/temp-shopify-app-cli/lib/shopify-cli/task.rb:7:in `call'
	 2: from /Users/duncanuszkay/src/github.com/Shopify/temp-shopify-app-cli/lib/shopify-cli/tasks/authenticate_identity.rb:15:in `call'
1: from /Users/duncanuszkay/src/github.com/Shopify/temp-shopify-app-cli/lib/shopify-cli/oauth.rb:59:in `authenticate'
/Users/duncanuszkay/src/github.com/Shopify/temp-shopify-app-cli/lib/shopify-cli/oauth.rb:113:in `receive_access_code': Timed out while waiting for response from shopify (ShopifyCli::OAuth::Error)
```

## Expected behavior

I'd expect to have a pretty generous timeout here given the human element involved. Or if not, a cleaner error message without a stacktrace telling me to retry since this is a pretty easy path to hit

## Actual behavior

I get an OAuth timeout error with a stacktrace and have to restart the command

## Steps to reproduce the problem

1. Start the authentication process
2. Wait
3. See the timeout error in the console

## Specifications

- App type: Node
- Operating System: macOS Catalina 10.15.2
- Shell: Bash
- Ruby version (ruby -v): 2.6.3

**Comment by tanema** [comment]
Currently the timeout is 60 seconds, it can be tweaked a bit more, I just don't want it hanging around too long if something else went wrong.
