### ISSUE TITLE
shopify-cli: command line "shopify server" fails run

### ISSUE THREAD

**Issue by rodgeraraujo** [Shopify/shopify-app-cli#490]
# Issue summary
After create a project, the command `shopify server` doesn't work as expected. Almost everything goes right, but i got a error message.

## Expected behavior

The command should execute the server for my project, work as expected.

## Actual behavior

I got this error message:

<details>
Please include this information in any issues/report along with relevant logs
/Users/rodger/.shopify-app-cli/lib/shopify-cli/tasks/update_dashboard_urls.rb:14:in `call': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Users/rodger/.shopify-app-cli/lib/shopify-cli/task.rb:7:in `call'
	from /Users/rodger/.shopify-app-cli/lib/shopify-cli/commands/serve.rb:23:in `setup'
	from /Users/rodger/.shopify-app-cli/lib/shopify-cli/commands/serve/node.rb:8:in `call'
	from /Users/rodger/.shopify-app-cli/lib/shopify-cli/app_type_command.rb:26:in `call'
	from /Users/rodger/.shopify-app-cli/lib/shopify-cli/command.rb:23:in `call'
	from /Users/rodger/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:17:in `block (2 levels) in call'
	from /Users/rodger/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:39:in `block (2 levels) in with_logging'
	from /Users/rodger/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:164:in `with_id'
	from /Users/rodger/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:38:in `block in with_logging'
	from /Users/rodger/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui.rb:143:in `log_output_to'
	from /Users/rodger/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `with_logging'
	from /Users/rodger/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
	from /Users/rodger/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:47:in `block (2 levels) in with_traps'
	from /Users/rodger/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
	from /Users/rodger/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:46:in `block in with_traps'
	from /Users/rodger/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
	from /Users/rodger/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `with_traps'
	from /Users/rodger/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
	from /Users/rodger/.shopify-app-cli/lib/shopify-cli/executor.rb:16:in `call'
	from /Users/rodger/.shopify-app-cli/lib/shopify-cli/entry_point.rb:16:in `block in call'
	from /Users/rodger/.shopify-app-cli/lib/shopify-cli/monorail/log.rb:44:in `event'
	from /Users/rodger/.shopify-app-cli/lib/shopify-cli/monorail/log.rb:28:in `invocation'
	from /Users/rodger/.shopify-app-cli/lib/shopify-cli/entry_point.rb:15:in `call'
	from /Users/rodger/.shopify-app-cli/bin/shopify:37:in `block in <main>'
	from /Users/rodger/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	from /Users/rodger/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	from /Users/rodger/.shopify-app-cli/bin/shopify:36:in `<main>'
</details>

## Steps to reproduce the problem

1. Create new app using command line shopify create project
2. Allow all priviledges and permissions to admin API
3. Run command line shopify server
4. Add all KEYs and Secrets (after that the error happens)

## Specifications

- App type: Public App
- Operating System: Mac OS 10.14.6
- Shell:  bash & zsh
- Ruby version (ruby -v): 2.3.7p456

**Comment by rodgeraraujo** [comment]
Fixed, uninstalling the CLI and reinstall.
