### ISSUE TITLE
Not able to create an app due to auth error

### ISSUE THREAD

**Issue by fremfi** [Shopify/shopify-app-cli#514]
# Issue summary

I get a timeout when I try to create a new project. The terminal opens up the browser, and once I choose my email address associated with the Partners account, then choose the development store I'd like to install the application. I am then logged in to my development store but I don't get prompted by the cli to choose the store anymore.

## Expected behavior

Shopify authorizes the cli to let me select the development store I would like to install my  application

## Actual behavior
```
? What type of app project would you like to create? (You chose: node embedded app)
This command ran with ID: 06591
Please include this information in any issues/report along with relevant logs
#<Thread:0x00007fd70686bed0@/Users/frederickmfinanga/.shopify-app-cli/lib/shopify-cli/oauth.rb:90 aborting> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	1: from /Users/frederickmfinanga/.shopify-app-cli/lib/shopify-cli/oauth.rb:106:in `block in listen_local'
/Users/frederickmfinanga/.shopify-app-cli/lib/shopify-cli/oauth.rb:105:in `ensure in block in listen_local': undefined method `close_write' for nil:NilClass (NoMethodError)
Traceback (most recent call last):
	41: from /Users/frederickmfinanga/.shopify-app-cli/bin/shopify:36:in `<main>'
	40: from /Users/frederickmfinanga/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	39: from /Users/frederickmfinanga/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	38: from /Users/frederickmfinanga/.shopify-app-cli/bin/shopify:37:in `block in <main>'
	37: from /Users/frederickmfinanga/.shopify-app-cli/lib/shopify-cli/entry_point.rb:15:in `call'
	36: from /Users/frederickmfinanga/.shopify-app-cli/lib/shopify-cli/monorail/log.rb:28:in `invocation'
	35: from /Users/frederickmfinanga/.shopify-app-cli/lib/shopify-cli/monorail/log.rb:44:in `event'
	34: from /Users/frederickmfinanga/.shopify-app-cli/lib/shopify-cli/entry_point.rb:16:in `block in call'
	33: from /Users/frederickmfinanga/.shopify-app-cli/lib/shopify-cli/executor.rb:16:in `call'
	32: from /Users/frederickmfinanga/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
	31: from /Users/frederickmfinanga/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `with_traps'
	30: from /Users/frederickmfinanga/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
	29: from /Users/frederickmfinanga/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:46:in `block in with_traps'
	28: from /Users/frederickmfinanga/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
	27: from /Users/frederickmfinanga/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:47:in `block (2 levels) in with_traps'
	26: from /Users/frederickmfinanga/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
	25: from /Users/frederickmfinanga/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `with_logging'
	24: from /Users/frederickmfinanga/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui.rb:143:in `log_output_to'
	23: from /Users/frederickmfinanga/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:38:in `block in with_logging'
	22: from /Users/frederickmfinanga/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:164:in `with_id'
	21: from /Users/frederickmfinanga/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:39:in `block (2 levels) in with_logging'
	20: from /Users/frederickmfinanga/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:17:in `block (2 levels) in call'
	19: from /Users/frederickmfinanga/.shopify-app-cli/lib/shopify-cli/command.rb:16:in `call'
	18: from /Users/frederickmfinanga/.shopify-app-cli/lib/shopify-cli/sub_command.rb:12:in `call'
	17: from /Users/frederickmfinanga/.shopify-app-cli/lib/shopify-cli/commands/create/project.rb:15:in `call'
	16: from /Users/frederickmfinanga/.shopify-app-cli/lib/shopify-cli/forms.rb:14:in `ask'
	15: from /Users/frederickmfinanga/.shopify-app-cli/lib/shopify-cli/forms/create_app.rb:13:in `ask'
	14: from /Users/frederickmfinanga/.shopify-app-cli/lib/shopify-cli/forms/create_app.rb:45:in `organization'
	13: from /Users/frederickmfinanga/.shopify-app-cli/lib/shopify-cli/forms/create_app.rb:37:in `organizations'
	12: from /Users/frederickmfinanga/.shopify-app-cli/lib/shopify-cli/helpers/organizations.rb:6:in `fetch_all'
	11: from /Users/frederickmfinanga/.shopify-app-cli/lib/shopify-cli/helpers/partners_api.rb:34:in `query'
	10: from /Users/frederickmfinanga/.shopify-app-cli/lib/shopify-cli/helpers/partners_api.rb:42:in `authenticated_req'
	 9: from /Users/frederickmfinanga/.shopify-app-cli/lib/shopify-cli/helpers/partners_api.rb:35:in `block in query'
	 8: from /Users/frederickmfinanga/.shopify-app-cli/lib/shopify-cli/helpers/partners_api.rb:53:in `api_client'
	 7: from /Users/frederickmfinanga/.shopify-app-cli/lib/shopify-cli/helpers/pkce_token.rb:6:in `read'
	 6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `get'
	 5: from /Users/frederickmfinanga/.shopify-app-cli/lib/shopify-cli/helpers/store.rb:37:in `get'
	 4: from /Users/frederickmfinanga/.shopify-app-cli/lib/shopify-cli/helpers/pkce_token.rb:7:in `block in read'
	 3: from /Users/frederickmfinanga/.shopify-app-cli/lib/shopify-cli/task.rb:7:in `call'
	 2: from /Users/frederickmfinanga/.shopify-app-cli/lib/shopify-cli/tasks/authenticate_identity.rb:15:in `call'
	 1: from /Users/frederickmfinanga/.shopify-app-cli/lib/shopify-cli/oauth.rb:60:in `authenticate'
/Users/frederickmfinanga/.shopify-app-cli/lib/shopify-cli/oauth.rb:132:in `receive_access_code': Timed out while waiting for response from shopify (ShopifyCli::OAuth::Error)
```

## Steps to reproduce the problem

1. shopify create project <appname>
2. Choose node embedded app

## Specifications

- App type:
- Operating System: Mac OS
- Shell: 
- Ruby version (ruby -v): ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]

**Comment by fremfi** [comment]
Randomly worked after trying again later
