### ISSUE TITLE
Failure to install ngrock on shopify serve

### ISSUE THREAD

**Issue by tballast** [Shopify/shopify-app-cli#519]
# Issue summary

Write a short description of the issue here ↓
When running `shopify serve` it fails to install ngrok

## Expected behavior

What do you think should happen?
It should install ngrok and start the server properly

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1.Using WSL create a project using `shopify create node my-proj`
2. run `shopify serve`
3. Get the following errors:

```
tballast@DRAGONS-DEN:~/git/tballast/shopify/shopify-app-cli-app/pickup-and-delivery-public$ shopify serve
/home/tballast/.shopify-app-cli/bin/support/load_shopify.rb:12: warning: Insecure world writable dir /home/tballast/.nvm/versions/node/v13.13.0 in PATH, mode 040777
#<Thread:0x00007ffff198c760@/home/tballast/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/spinner/spin_group.rb:43 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        7: from /home/tballast/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/spinner/spin_group.rb:46:in `block in initialize'
        6: from /home/tballast/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:120:in `run'
        5: from /home/tballast/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:91:in `with_stdin_masked'
        4: from /home/tballast/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:132:in `block in run'
        3: from /home/tballast/.shopify-app-cli/lib/shopify-cli/tasks/tunnel.rb:60:in `block in install'
        2: from /home/tballast/.shopify-app-cli/lib/shopify-cli/context/system.rb:51:in `system'
        1: from /home/tballast/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/system.rb:114:in `system'
/home/tballast/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/system.rb:114:in `spawn': no implicit conversion of nil into String (TypeError)
✗ Installing ngrok...
┏━━ Task Failed: Installing ngrok... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ TypeError: no implicit conversion of nil into String
┃       from /home/tballast/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/system.rb:114:in `spawn'
┃       from /home/tballast/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/system.rb:114:in `system'
┃       from /home/tballast/.shopify-app-cli/lib/shopify-cli/context/system.rb:51:in `system'
┃       from /home/tballast/.shopify-app-cli/lib/shopify-cli/tasks/tunnel.rb:60:in `block in install'
┃       from /home/tballast/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:132:in `block in run'
┃       from /home/tballast/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:91:in `with_stdin_masked'
┃       from /home/tballast/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:120:in `run'
┃       from /home/tballast/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/spinner/spin_group.rb:46:in `block in initialize'
┣━━ STDOUT ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ (empty)
┣━━ STDERR ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ (empty)
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (0.01s) ━━
x ngrok tunnel stopped
This command ran with ID: 01337
Please include this information in any issues/report along with relevant logs
Traceback (most recent call last):
        28: from /home/tballast/.shopify-app-cli/bin/shopify:36:in `<main>'
        27: from /home/tballast/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        26: from /home/tballast/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        25: from /home/tballast/.shopify-app-cli/bin/shopify:37:in `block in <main>'
        24: from /home/tballast/.shopify-app-cli/lib/shopify-cli/core/entry_point.rb:18:in `call'
        23: from /home/tballast/.shopify-app-cli/lib/shopify-cli/core/monorail/log.rb:29:in `invocation'
        22: from /home/tballast/.shopify-app-cli/lib/shopify-cli/core/monorail/log.rb:45:in `event'
        21: from /home/tballast/.shopify-app-cli/lib/shopify-cli/core/entry_point.rb:19:in `block in call'
        20: from /home/tballast/.shopify-app-cli/lib/shopify-cli/core/executor.rb:17:in `call'
        19: from /home/tballast/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        18: from /home/tballast/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `with_traps'
        17: from /home/tballast/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
        16: from /home/tballast/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:46:in `block in with_traps'
        15: from /home/tballast/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:53:in `twrap'
        14: from /home/tballast/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:47:in `block (2 levels) in with_traps'
        13: from /home/tballast/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
        12: from /home/tballast/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `with_logging'
        11: from /home/tballast/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui.rb:143:in `log_output_to'
        10: from /home/tballast/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:38:in `block in with_logging'
         9: from /home/tballast/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:164:in `with_id'
         8: from /home/tballast/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:39:in `block (2 levels) in with_logging'
         7: from /home/tballast/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:17:in `block (2 levels) in call'
         6: from /home/tballast/.shopify-app-cli/lib/shopify-cli/command.rb:24:in `call'
         5: from /home/tballast/.shopify-app-cli/lib/project_types/node/commands/serve.rb:15:in `call'
         4: from /home/tballast/.shopify-app-cli/lib/shopify-cli/task.rb:7:in `call'
         3: from /home/tballast/.shopify-app-cli/lib/shopify-cli/tasks/tunnel.rb:19:in `call'
         2: from /home/tballast/.shopify-app-cli/lib/shopify-cli/tasks/tunnel.rb:37:in `start'
         1: from /home/tballast/.shopify-app-cli/lib/shopify-cli/tasks/tunnel.rb:68:in `fetch_url'
/home/tballast/.shopify-app-cli/lib/shopify-cli/tasks/tunnel.rb:72:in `rescue in fetch_url': Unable to fetch external url (ShopifyCli::Tasks::Tunnel::FetchUrlError)
```

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

## Specifications

- App type: Public (ie multi merchant)
- Operating System: Windows 10, using Windows Subsystem for Linux
- Shell: bash, version 4.4.20(1)-release
- Ruby version (ruby -v): ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]

**Comment by tanema** [comment]
Can you check if `~/.shopify-app-cli/ngrok.zip` exists? Can you also paste here the output of `uname -a`?

**Comment by Kazebr** [comment]
I was getting the same error with the same systems specifications.

`uname -a` results:

Linux DESKTOP-I83UCGG 4.4.0-17763-Microsoft #864-Microsoft Thu Nov 07 15:22:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux

ngrok.zip was missing, so I ran this command to download:

`wget -O ~/.shopify-app-cli/ngrok.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip`

re-running `shopify serve`  got past the error

**Comment by tanema** [comment]
Do either of you have `curl` on your machine?

**Comment by Kazebr** [comment]
Yes,

Here is my `curl --version`

curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
