### ISSUE TITLE
shopify create:  `spawn': No such file or directory - node (Errno::ENOENT)

### ISSUE THREAD

**Issue by neil-rubens** [Shopify/shopify-app-cli#552]
On Windows (from Ubuntu WSL)

when running `shopify create`

am getting the following error:

```
Traceback (most recent call last):
        33: from /home/neil/.shopify-app-cli/bin/shopify:36:in `<main>'
        32: from /home/neil/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        31: from /home/neil/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        30: from /home/neil/.shopify-app-cli/bin/shopify:37:in `block in <main>'
        29: from /home/neil/.shopify-app-cli/lib/shopify-cli/core/entry_point.rb:18:in `call'
        28: from /home/neil/.shopify-app-cli/lib/shopify-cli/core/monorail.rb:25:in `log'
        27: from /home/neil/.shopify-app-cli/lib/shopify-cli/core/entry_point.rb:19:in `block in call'
        26: from /home/neil/.shopify-app-cli/lib/shopify-cli/core/executor.rb:17:in `call'
        25: from /home/neil/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        24: from /home/neil/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `with_traps'
        23: from /home/neil/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
        22: from /home/neil/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:46:in `block in with_traps'
        21: from /home/neil/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:53:in `twrap'
        20: from /home/neil/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:47:in `block (2 levels) in with_traps'
        19: from /home/neil/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
        18: from /home/neil/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `with_logging'
        17: from /home/neil/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui.rb:143:in `log_output_to'
        16: from /home/neil/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:38:in `block in with_logging'
        15: from /home/neil/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:164:in `with_id'
        14: from /home/neil/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:39:in `block (2 levels) in with_logging'
        13: from /home/neil/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:17:in `block (2 levels) in call'
        12: from /home/neil/.shopify-app-cli/lib/shopify-cli/commands/create.rb:8:in `call'
        11: from /home/neil/.shopify-app-cli/lib/shopify-cli/command.rb:24:in `call'
        10: from /home/neil/.shopify-app-cli/lib/shopify-cli/commands/create.rb:25:in `call'
         9: from /home/neil/.shopify-app-cli/lib/shopify-cli/sub_command.rb:12:in `call'
         8: from /home/neil/.shopify-app-cli/lib/project_types/node/commands/create.rb:26:in `call'
         7: from /home/neil/.shopify-app-cli/lib/project_types/node/commands/create.rb:72:in `check_node'
         6: from /home/neil/.shopify-app-cli/lib/shopify-cli/context.rb:268:in `capture2e'
         5: from /home/neil/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/system.rb:68:in `capture2e'
         4: from /home/neil/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/system.rb:176:in `delegate_open3'
         3: from /usr/lib/ruby/2.7.0/open3.rb:390:in `capture2e'
         2: from /usr/lib/ruby/2.7.0/open3.rb:208:in `popen2e'
         1: from /usr/lib/ruby/2.7.0/open3.rb:213:in `popen_run'
/usr/lib/ruby/2.7.0/open3.rb:213:in `spawn': No such file or directory - node (Errno::ENOENT)
```

**Comment by tanema** [comment]
We should handle this better but it seems like you don't have node installed. We will try to fix this soon.

**Comment by neil-rubens** [comment]
Thanks a lot @tanema 
Installing **node** fixed the error  (nodejs on ubuntu)

p.s. afterwards needed to also install **npm** since on `shopify create` was getting the following error:
```
Using Development Store ooo.myshopify.com
✓ node v10.19.0
: not foundc/Program Files/nodejs//npm: 3:
: not foundram Files/nodejs//npm: 5:
/mnt/c/Program Files/nodejs//npm: 6: Syntax error: word unexpected (expecting "in")
```

Am keeping the issue open; since it would useful if the error would be less cryptic.
