### ISSUE TITLE
App cannot be installed using this link error

### ISSUE THREAD

**Issue by DuncanUszkay1** [Shopify/shopify-app-cli#570]
# Issue summary

When trying to install a node app, I get this error:

![image](https://user-images.githubusercontent.com/8670351/81025949-877a1000-8e46-11ea-8d1b-007fa7722eca.png)

## Expected behavior

This should allow me to install

## Actual behavior

I get the error message shown above, as well as this output in my console:
```
SIGINFO:
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/system.rb:131:in `call'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/system.rb:131:in `select'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/system.rb:131:in `block in system'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/system.rb:127:in `loop'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/system.rb:127:in `system'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/lib/shopify-cli/context.rb:228:in `system'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/lib/project_types/node/commands/serve.rb:32:in `block in call'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/frame.rb:82:in `open'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/lib/project_types/node/commands/serve.rb:29:in `call'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/lib/shopify-cli/command.rb:24:in `call'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:17:in `block (2 levels) in call'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:39:in `block (2 levels) in with_logging'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:164:in `with_id'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:38:in `block in with_logging'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui.rb:143:in `log_output_to'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `with_logging'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:47:in `block (2 levels) in with_traps'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:46:in `block in with_traps'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `with_traps'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/lib/shopify-cli/core/executor.rb:17:in `call'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/lib/shopify-cli/core/entry_point.rb:19:in `block in call'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/lib/shopify-cli/core/monorail.rb:25:in `log'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/lib/shopify-cli/core/entry_point.rb:18:in `call'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/bin/shopify:37:in `block in <main>'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
/Users/duncanuszkay/src/github.com/Shopify/shopify-app-cli/bin/shopify:36:in `<main>'
```
This output appears after opening the link.

## Steps to reproduce the problem

1. clone the latest version of this repo
1. `shopify load-dev /path/to/repo`
1. `shopify create`
4. select node
5. `shopify serve`
6. Hit Control-T to open up in the installation link in the browser

## Specifications

- App type: Node
- Operating System: OSX 10.15.4
- Shell: bash
- Ruby version (ruby -v): 2.5.1

**Comment by tanema** [comment]
The `SIGINFO` error has nothing to do with your issue it will just present itself sometimes when you press ctrl-t. Please reach out to the partners dashboard to find clarity on why you cannot install your app.

**Comment by paulomarg** [comment]
I'm closing this issue as it does not seem to be related to the CLI itself. Please feel free to reopen if you think the problem might be in the CLI after all and we'll look into it.
