### ISSUE TITLE
Populate command fails due to admin_api exception

### ISSUE THREAD

**Issue by ow** [Shopify/shopify-app-cli#651]
# Issue summary
Write a short description of the issue here ↓

Building on #650, I found that after getting `shopify populate` set up, I was unable to populate any products or orders, due to an exception on the `admin_api` gem:

```
Traceback (most recent call last):
        31: from /Users/owenwilliams/.shopify-app-cli/bin/shopify:36:in `<main>'
        30: from /Users/owenwilliams/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        29: from /Users/owenwilliams/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        28: from /Users/owenwilliams/.shopify-app-cli/bin/shopify:37:in `block in <main>'
        27: from /Users/owenwilliams/.shopify-app-cli/lib/shopify-cli/core/entry_point.rb:18:in `call'
        26: from /Users/owenwilliams/.shopify-app-cli/lib/shopify-cli/core/monorail.rb:26:in `log'
        25: from /Users/owenwilliams/.shopify-app-cli/lib/shopify-cli/core/entry_point.rb:19:in `block in call'
        24: from /Users/owenwilliams/.shopify-app-cli/lib/shopify-cli/core/executor.rb:17:in `call'
        23: from /Users/owenwilliams/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        22: from /Users/owenwilliams/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `with_traps'
        21: from /Users/owenwilliams/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
        20: from /Users/owenwilliams/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:46:in `block in with_traps'
        19: from /Users/owenwilliams/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
        18: from /Users/owenwilliams/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:47:in `block (2 levels) in with_traps'
        17: from /Users/owenwilliams/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
        16: from /Users/owenwilliams/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `with_logging'
        15: from /Users/owenwilliams/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui.rb:143:in `log_output_to'
        14: from /Users/owenwilliams/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:38:in `block in with_logging'
        13: from /Users/owenwilliams/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:164:in `with_id'
        12: from /Users/owenwilliams/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:39:in `block (2 levels) in with_logging'
        11: from /Users/owenwilliams/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:17:in `block (2 levels) in call'
        10: from /Users/owenwilliams/.shopify-app-cli/lib/shopify-cli/command.rb:17:in `call'
         9: from /Users/owenwilliams/.shopify-app-cli/lib/shopify-cli/admin_api/populate_resource_command.rb:17:in `call'
         8: from /Users/owenwilliams/.shopify-app-cli/lib/shopify-cli/admin_api/populate_resource_command.rb:34:in `call'
         7: from /Users/owenwilliams/.shopify-app-cli/lib/shopify-cli/admin_api/populate_resource_command.rb:101:in `input_options'
         6: from /Users/owenwilliams/.shopify-app-cli/lib/shopify-cli/admin_api/populate_resource_command.rb:112:in `schema'
         5: from /Users/owenwilliams/.shopify-app-cli/lib/shopify-cli/admin_api/schema.rb:8:in `get'
         4: from /Users/owenwilliams/.shopify-app-cli/lib/shopify-cli/admin_api.rb:42:in `query'
         3: from /Users/owenwilliams/.shopify-app-cli/lib/shopify-cli/admin_api.rb:50:in `authenticated_req'
         2: from /Users/owenwilliams/.shopify-app-cli/lib/shopify-cli/admin_api.rb:43:in `block in query'
         1: from /Users/owenwilliams/.shopify-app-cli/lib/shopify-cli/admin_api.rb:74:in `api_client'
/Users/owenwilliams/.shopify-app-cli/lib/shopify-cli/admin_api.rb:93:in **`fetch_api_version': undefined method** `[]' for nil:NilClass (NoMethodError)
```

It looks like the API now requires passing which API version you want to use, so it can't proceed.

## Expected behavior
What do you think should happen?

Populate some products :)

## Actual behavior

What actually happens?

No populated products. 
Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1. Run `shopify populate` on a repo that's set up
2. Get the error

## Specifications

- Operating System: macOS 10.15.5
- Ruby version (ruby -v): ruby 2.6.3p62

**Comment by tanema** [comment]
@paulomarg @mkevinosullivan Did this get fixed when you fixed the schema call?

**Comment by paulomarg** [comment]
This is working for me on `main` right now, and the schema is fixed here. That is the same symptom we saw before we fixed that.
