### ISSUE TITLE
Can't create an app ! 

### ISSUE THREAD

**Issue by nemoeric** [Shopify/shopify-app-cli#732]
[EDIT] : I created one partner account with one email and it does work with current environment.
Which would mean that the problem might come from the fact that my original email account is linked to multiple partner accounts ?  

# Issue summary
Hey, 
I am trying to create a node app through the CLI but it shows an error right after I pick the app type.

```
✗ An unexpected error occurred on Shopify.
This command ran with ID: 80268

Please include this information in any issues/report along with relevant logs
Traceback (most recent call last):
        30: from /Users/ericnemo/.shopify-app-cli/bin/shopify:36:in `<main>'
        29: from /Users/ericnemo/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        28: from /Users/ericnemo/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        27: from /Users/ericnemo/.shopify-app-cli/bin/shopify:37:in `block in <main>'
        26: from /Users/ericnemo/.shopify-app-cli/lib/shopify-cli/core/entry_point.rb:18:in `call'
        25: from /Users/ericnemo/.shopify-app-cli/lib/shopify-cli/core/monorail.rb:32:in `log'
        24: from /Users/ericnemo/.shopify-app-cli/lib/shopify-cli/core/entry_point.rb:19:in `block in call'
        23: from /Users/ericnemo/.shopify-app-cli/lib/shopify-cli/core/executor.rb:17:in `call'
        22: from /Users/ericnemo/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        21: from /Users/ericnemo/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `with_traps'
        20: from /Users/ericnemo/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
        19: from /Users/ericnemo/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:46:in `block in with_traps'
        18: from /Users/ericnemo/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
        17: from /Users/ericnemo/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:47:in `block (2 levels) in with_traps'
        16: from /Users/ericnemo/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
        15: from /Users/ericnemo/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `with_logging'
        14: from /Users/ericnemo/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui.rb:143:in `log_output_to'
        13: from /Users/ericnemo/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:38:in `block in with_logging'
        12: from /Users/ericnemo/.shopify-app-cli/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:164:in `with_id'
        11: from /Users/ericnemo/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:39:in `block (2 levels) in with_logging'
        10: from /Users/ericnemo/.shopify-app-cli/vendor/deps/cli-kit/lib/cli/kit/executor.rb:17:in `block (2 levels) in call'
         9: from /Users/ericnemo/.shopify-app-cli/lib/shopify-cli/commands/create.rb:8:in `call'
         8: from /Users/ericnemo/.shopify-app-cli/lib/shopify-cli/command.rb:22:in `call'
         7: from /Users/ericnemo/.shopify-app-cli/lib/shopify-cli/commands/create.rb:25:in `call'
         6: from /Users/ericnemo/.shopify-app-cli/lib/shopify-cli/sub_command.rb:11:in `call'
         5: from /Users/ericnemo/.shopify-app-cli/lib/project_types/node/commands/create.rb:16:in `call'
         4: from /Users/ericnemo/.shopify-app-cli/lib/shopify-cli/form.rb:13:in `ask'
         3: from /Users/ericnemo/.shopify-app-cli/lib/project_types/node/forms/create.rb:13:in `ask'
         2: from /Users/ericnemo/.shopify-app-cli/lib/project_types/node/forms/create.rb:46:in `organization'
         1: from /Users/ericnemo/.shopify-app-cli/lib/project_types/node/forms/create.rb:35:in `organizations'
/Users/ericnemo/.shopify-app-cli/lib/shopify-cli/partners_api/organizations.rb:7:in `fetch_all': undefined method `[]' for nil:NilClass (NoMethodError)
```

Thanks for your help! 

## Specifications

- App type: node
- Operating System: Catalina 10.15.5
- Node version : 12.18.1 and tried also with 10.9.9

**Comment by tanema** [comment]
Yes it looks like you were not appropriately signed up, however we should handle this in a more graceful way.
