### ISSUE TITLE
CLI authentication fails after authorizing in browser

### ISSUE THREAD

**Issue by igrigorik** [Shopify/shopify-app-cli#751]
## Expected behavior
1. Copy the URL into the browser and load
1. Log in into partner account
1. CLI should successfully complete the auth

## Actual behavior

After logging in into the partner dashboard via provided the URL the CLI errors out with no useful feedback.

```
~ » shopify connect                                                                                                                                                                                           
? What type of project would you like to connect? (You chose: Ruby on Rails App)
𝒾 Authentication required. Login to the URL below with your Shopify Partners account credentials to continue.
Please open this URL in your browser:
https://accounts.shopify.com/oauth/authorize?client_id=<redacted>
This command ran with ID: 45116
Please include this information in any issues/report along with relevant logs
Traceback (most recent call last):
	25: from /usr/local/Cellar/shopify-cli/1.0.1/src/bin/shopify:30:in `<main>'
	24: from /usr/local/Cellar/shopify-cli/1.0.1/src/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	23: from /usr/local/Cellar/shopify-cli/1.0.1/src/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	22: from /usr/local/Cellar/shopify-cli/1.0.1/src/bin/shopify:31:in `block in <main>'
	21: from /usr/local/Cellar/shopify-cli/1.0.1/src/lib/shopify-cli/core/entry_point.rb:39:in `call'
	20: from /usr/local/Cellar/shopify-cli/1.0.1/src/lib/shopify-cli/core/monorail.rb:20:in `log'
	19: from /usr/local/Cellar/shopify-cli/1.0.1/src/lib/shopify-cli/core/entry_point.rb:40:in `block in call'
	18: from /usr/local/Cellar/shopify-cli/1.0.1/src/lib/shopify-cli/core/executor.rb:17:in `call'
	17: from /usr/local/Cellar/shopify-cli/1.0.1/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
	16: from /usr/local/Cellar/shopify-cli/1.0.1/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `with_traps'
	15: from /usr/local/Cellar/shopify-cli/1.0.1/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
	14: from /usr/local/Cellar/shopify-cli/1.0.1/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:46:in `block in with_traps'
	13: from /usr/local/Cellar/shopify-cli/1.0.1/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
	12: from /usr/local/Cellar/shopify-cli/1.0.1/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:47:in `block (2 levels) in with_traps'
	11: from /usr/local/Cellar/shopify-cli/1.0.1/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
	10: from /usr/local/Cellar/shopify-cli/1.0.1/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `with_logging'
	 9: from /usr/local/Cellar/shopify-cli/1.0.1/src/vendor/deps/cli-ui/lib/cli/ui.rb:171:in `log_output_to'
	 8: from /usr/local/Cellar/shopify-cli/1.0.1/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:38:in `block in with_logging'
	 7: from /usr/local/Cellar/shopify-cli/1.0.1/src/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
	 6: from /usr/local/Cellar/shopify-cli/1.0.1/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:39:in `block (2 levels) in with_logging'
	 5: from /usr/local/Cellar/shopify-cli/1.0.1/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:17:in `block (2 levels) in call'
	 4: from /usr/local/Cellar/shopify-cli/1.0.1/src/lib/shopify-cli/command.rb:22:in `call'
	 3: from /usr/local/Cellar/shopify-cli/1.0.1/src/lib/shopify-cli/commands/connect.rb:23:in `call'
	 2: from /usr/local/Cellar/shopify-cli/1.0.1/src/lib/shopify-cli/commands/connect.rb:61:in `get_app'
	 1: from /usr/local/Cellar/shopify-cli/1.0.1/src/vendor/deps/cli-ui/lib/cli/ui/prompt.rb:100:in `ask'
/usr/local/Cellar/shopify-cli/1.0.1/src/vendor/deps/cli-ui/lib/cli/ui/prompt.rb:192:in `ask_interactive': insufficient options (ArgumentError)
```

## Steps to reproduce the problem
1. Install shopify gem, or homebrew..
1. run `shopify connect`

## Specifications

- Operating System: OSX 10.15.5
- Shell: zsh 
- Ruby version (ruby -v): ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin19]

**Comment by igrigorik** [comment]
FWIW, after this fails, running `shopify create` does succeed, so it looks like the auth did work but errored out when presenting the results?

**Comment by tanema** [comment]
Hey @igrigorik have you updated your CLI? This does not happen in the most recent version for me.

**Comment by tanema** [comment]
Ah actually I have a hunch that `connect` will now work after you have created an app. Did you have any apps before running this?

**Comment by igrigorik** [comment]
@tanema no, I did not, blank account with no development stores or apps. Basically, I just followed one of the Unite demos: create the account, install the CLI, try to use it to bootstrap the app and stores. 

Since we're on the subject, one thing that *was* confusing: I expect `shopify connect` to, well, connect and get the credentials established. Instead, it immediately prompted me to choose the stack and create an app -- seems backwards.

**Comment by tanema** [comment]
Ah yes this is an interesting point to note. `connect` is meant to rather `re-connect` a shopify project to it's existing credentials (api key and secret) so that the developer does not need to store their `.env` file in the repo. This makes the projects a lot easier to share from one developer to another. Thanks for the friction log and this note we will definitely use this feedback

**Comment by sagar-ranglani** [comment]
Any updates on this? Suddenly `shopify node serve` stopped working with

```
$ shopify node serve                                    
✗ An unexpected error occurred on Shopify.
✗ Couldn't verify your store xxxxxx.myshopify.com
```

And `shopify node connect` with:

```
! Warning: if you have connected to an app in production, running serve may update the app URL and cause an outage.
! This app appears to be already connected
✗ An unexpected error occurred on Shopify.
This command ran with ID: 53836
Please include this information in any issues/report along with relevant logs
/usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-ui/lib/cli/ui/prompt.rb:192:in `ask_interactive': insufficient options (ArgumentError)
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-ui/lib/cli/ui/prompt.rb:100:in `ask'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/tasks/ensure_env.rb:32:in `fetch_org'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/tasks/ensure_env.rb:17:in `call'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/task.rb:7:in `call'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/connect.rb:13:in `default_connect'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/project_types/node/commands/connect.rb:12:in `call'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/sub_command.rb:13:in `call'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/command.rb:19:in `call'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/core/executor.rb:15:in `call'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/core/entry_point.rb:24:in `block in call'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/core/monorail.rb:32:in `log'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/lib/shopify-cli/core/entry_point.rb:23:in `call'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/bin/shopify:33:in `block in <top (required)>'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        from /usr/local/Cellar/shopify-cli/2.3.0/gems/shopify-cli-2.3.0/bin/shopify:32:in `<top (required)>'
        from /usr/local/bin/shopify:6:in `load'
        from /usr/local/bin/shopify:6:in `<main>'
```
