### ISSUE TITLE
shopify generate webhook error

### ISSUE THREAD

**Issue by jezsung** [Shopify/shopify-app-cli#754]
This is a new fresh app created with the `shopify create node` command. I ran the `shopify generate webhook APP_UNINSTALLED`  and the blow is its log. The CLI version is 1.0.1.

```
jezsung@DESKTOP-AG2190I:/mnt/d/shopifyapps/safe-paypal$ shopify generate webhook APP_UNINSTALLED
/var/lib/gems/2.7.0/gems/shopify-cli-1.0.1/lib/shopify-cli/core/executor.rb:9: warning: Using the last argument as keyword parameters is deprecated; maybe ** should 
be added to the call
/var/lib/gems/2.7.0/gems/shopify-cli-1.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:8: warning: The called method `initialize' is defined here
This command ran with ID: 24225
Please include this information in any issues/report along with relevant logs
Traceback (most recent call last):
        25: from /var/lib/gems/2.7.0/gems/shopify-cli-1.0.1/bin/shopify:30:in `<main>'
        24: from /var/lib/gems/2.7.0/gems/shopify-cli-1.0.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'        
        23: from /var/lib/gems/2.7.0/gems/shopify-cli-1.0.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        22: from /var/lib/gems/2.7.0/gems/shopify-cli-1.0.1/bin/shopify:31:in `block in <main>'
        21: from /var/lib/gems/2.7.0/gems/shopify-cli-1.0.1/lib/shopify-cli/core/entry_point.rb:39:in `call'
        20: from /var/lib/gems/2.7.0/gems/shopify-cli-1.0.1/lib/shopify-cli/core/monorail.rb:20:in `log'    
        19: from /var/lib/gems/2.7.0/gems/shopify-cli-1.0.1/lib/shopify-cli/core/entry_point.rb:40:in `block in call'
        18: from /var/lib/gems/2.7.0/gems/shopify-cli-1.0.1/lib/shopify-cli/core/executor.rb:17:in `call'
        17: from /var/lib/gems/2.7.0/gems/shopify-cli-1.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        16: from /var/lib/gems/2.7.0/gems/shopify-cli-1.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `with_traps'
        15: from /var/lib/gems/2.7.0/gems/shopify-cli-1.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
        14: from /var/lib/gems/2.7.0/gems/shopify-cli-1.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:46:in `block in with_traps'
        13: from /var/lib/gems/2.7.0/gems/shopify-cli-1.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:53:in `twrap'
        12: from /var/lib/gems/2.7.0/gems/shopify-cli-1.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:47:in `block (2 levels) in with_traps'
        11: from /var/lib/gems/2.7.0/gems/shopify-cli-1.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
        10: from /var/lib/gems/2.7.0/gems/shopify-cli-1.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `with_logging'
         9: from /var/lib/gems/2.7.0/gems/shopify-cli-1.0.1/vendor/deps/cli-ui/lib/cli/ui.rb:171:in `log_output_to'
         8: from /var/lib/gems/2.7.0/gems/shopify-cli-1.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:38:in `block in with_logging'
         7: from /var/lib/gems/2.7.0/gems/shopify-cli-1.0.1/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
         6: from /var/lib/gems/2.7.0/gems/shopify-cli-1.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:39:in `block (2 levels) in with_logging'
         5: from /var/lib/gems/2.7.0/gems/shopify-cli-1.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:17:in `block (2 levels) in call'
         4: from /var/lib/gems/2.7.0/gems/shopify-cli-1.0.1/lib/shopify-cli/command.rb:17:in `call'
         3: from /var/lib/gems/2.7.0/gems/shopify-cli-1.0.1/lib/shopify-cli/sub_command.rb:11:in `call'
         2: from /var/lib/gems/2.7.0/gems/shopify-cli-1.0.1/lib/project_types/node/commands/generate/webhook.rb:9:in `call'
         1: from /var/lib/gems/2.7.0/gems/shopify-cli-1.0.1/lib/shopify-cli/admin_api/schema.rb:8:in `get'
/var/lib/gems/2.7.0/gems/shopify-cli-1.0.1/lib/shopify-cli/admin_api.rb:40:in `query': missing keyword: :shop (ArgumentError)
```

**Comment by tomcdisco** [comment]
i'm getting this exact same error when i run
`shopify populate products`

**Comment by jezsung** [comment]
> i'm getting this exact same error when i run
> `shopify populate products`

Me too... every `populate` command doesn't work as well. I'm not sure if it's a bug only on new version. Did you upgrade your cli to 1.0.1?

**Comment by mkevinosullivan** [comment]
@tomcdisco @jezsung Please update to v1.0.2 of the CLI; it should now work.

**Comment by igrigorik** [comment]
Can confirm that the issue went away after 1.0.2. update -- ty!
