### ISSUE TITLE
Error when connect first time :  `fetch_with_app': undefined method `[]' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by ShirasuGyoza** [Shopify/shopify-app-cli#763]
# Issue summary
Hi, our new joined member faces an error below when they run `shopify serve` or `shipify create` using Shopify app cli v1.0.2.

## Expected behavior
`shopify serve` to connect app and serve ngrok url.

## Actual behavior
This error occurred after authorized through `shopify serve` or `shopify create` :

<details>✗ An unexpected error occurred on Shopify.
This command ran with ID: 68070
Please include this information in any issues/report along with relevant logs
Traceback (most recent call last):
        24: from /usr/local/Cellar/shopify-cli/1.0.2/src/bin/shopify:30:in `<main>'
        23: from /usr/local/Cellar/shopify-cli/1.0.2/src/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        22: from /usr/local/Cellar/shopify-cli/1.0.2/src/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        21: from /usr/local/Cellar/shopify-cli/1.0.2/src/bin/shopify:31:in `block in <main>'
        20: from /usr/local/Cellar/shopify-cli/1.0.2/src/lib/shopify-cli/core/entry_point.rb:39:in `call'
        19: from /usr/local/Cellar/shopify-cli/1.0.2/src/lib/shopify-cli/core/monorail.rb:32:in `log'
        18: from /usr/local/Cellar/shopify-cli/1.0.2/src/lib/shopify-cli/core/entry_point.rb:40:in `block in call'
        17: from /usr/local/Cellar/shopify-cli/1.0.2/src/lib/shopify-cli/core/executor.rb:17:in `call'
        16: from /usr/local/Cellar/shopify-cli/1.0.2/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        15: from /usr/local/Cellar/shopify-cli/1.0.2/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `with_traps'
        14: from /usr/local/Cellar/shopify-cli/1.0.2/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
        13: from /usr/local/Cellar/shopify-cli/1.0.2/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:46:in `block in with_traps'
        12: from /usr/local/Cellar/shopify-cli/1.0.2/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
        11: from /usr/local/Cellar/shopify-cli/1.0.2/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:47:in `block (2 levels) in with_traps'
        10: from /usr/local/Cellar/shopify-cli/1.0.2/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
         9: from /usr/local/Cellar/shopify-cli/1.0.2/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `with_logging'
         8: from /usr/local/Cellar/shopify-cli/1.0.2/src/vendor/deps/cli-ui/lib/cli/ui.rb:171:in `log_output_to'
         7: from /usr/local/Cellar/shopify-cli/1.0.2/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:38:in `block in with_logging'
         6: from /usr/local/Cellar/shopify-cli/1.0.2/src/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
         5: from /usr/local/Cellar/shopify-cli/1.0.2/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:39:in `block (2 levels) in with_logging'
         4: from /usr/local/Cellar/shopify-cli/1.0.2/src/vendor/deps/cli-kit/lib/cli/kit/executor.rb:17:in `block (2 levels) in call'
         3: from /usr/local/Cellar/shopify-cli/1.0.2/src/lib/shopify-cli/command.rb:22:in `call'
         2: from /usr/local/Cellar/shopify-cli/1.0.2/src/lib/shopify-cli/commands/connect.rb:21:in `call'
         1: from /usr/local/Cellar/shopify-cli/1.0.2/src/lib/shopify-cli/commands/connect.rb:41:in `fetch_org'
/usr/local/Cellar/shopify-cli/1.0.2/src/lib/shopify-cli/partners_api/organizations.rb:23:in `fetch_with_app': undefined method `[]' for nil:NilClass (NoMethodError)</details>

## Specifications
- app version: v1.0.2
- bash
- ruby v2.6.3
- partner dashboard, development store and test app created before connecting with cli
- hasn't connected before using older version of Shopify app cli (I don't know this is related or not)

**Comment by ShirasuGyoza** [comment]
Solved by re-create new Shopify partner account.
