### ISSUE TITLE
shopify connect fails after authenticating successfully

### ISSUE THREAD

**Issue by maxilevi** [Shopify/shopify-app-cli#791]
# Issue summary

When using `shopify connect` on an existing project the command fails after authenticating successfully on the browser.

## Expected behavior

Sucessfully connect to my partner shopify account

## Actual behavior

Command fails and throws the following error:

```
This command ran with ID: 96873
Please include this information in any issues/report along with relevant logs
Traceback (most recent call last):
        35: from /var/lib/gems/2.5.0/gems/shopify-cli-1.0.0/bin/shopify:30:in `<main>'
        34: from /var/lib/gems/2.5.0/gems/shopify-cli-1.0.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
        33: from /var/lib/gems/2.5.0/gems/shopify-cli-1.0.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
        32: from /var/lib/gems/2.5.0/gems/shopify-cli-1.0.0/bin/shopify:31:in `block in <main>'
        31: from /var/lib/gems/2.5.0/gems/shopify-cli-1.0.0/lib/shopify-cli/core/entry_point.rb:33:in `call'
        30: from /var/lib/gems/2.5.0/gems/shopify-cli-1.0.0/lib/shopify-cli/core/monorail.rb:20:in `log'
        29: from /var/lib/gems/2.5.0/gems/shopify-cli-1.0.0/lib/shopify-cli/core/entry_point.rb:34:in `block in call'
        28: from /var/lib/gems/2.5.0/gems/shopify-cli-1.0.0/lib/shopify-cli/core/executor.rb:17:in `call'
        27: from /var/lib/gems/2.5.0/gems/shopify-cli-1.0.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
        26: from /var/lib/gems/2.5.0/gems/shopify-cli-1.0.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `with_traps'
        25: from /var/lib/gems/2.5.0/gems/shopify-cli-1.0.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:57:in `twrap'
        24: from /var/lib/gems/2.5.0/gems/shopify-cli-1.0.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:46:in `block in with_traps'
        23: from /var/lib/gems/2.5.0/gems/shopify-cli-1.0.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:53:in `twrap'
        22: from /var/lib/gems/2.5.0/gems/shopify-cli-1.0.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:47:in `block (2 levels) in with_traps'
        21: from /var/lib/gems/2.5.0/gems/shopify-cli-1.0.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
        20: from /var/lib/gems/2.5.0/gems/shopify-cli-1.0.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `with_logging'
        19: from /var/lib/gems/2.5.0/gems/shopify-cli-1.0.0/vendor/deps/cli-ui/lib/cli/ui.rb:171:in `log_output_to'
        18: from /var/lib/gems/2.5.0/gems/shopify-cli-1.0.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:38:in `block in with_logging'
        17: from /var/lib/gems/2.5.0/gems/shopify-cli-1.0.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
        16: from /var/lib/gems/2.5.0/gems/shopify-cli-1.0.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:39:in `block (2 levels) in with_logging'
        15: from /var/lib/gems/2.5.0/gems/shopify-cli-1.0.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:17:in `block (2 levels) in call'
        14: from /var/lib/gems/2.5.0/gems/shopify-cli-1.0.0/lib/shopify-cli/command.rb:22:in `call'
        13: from /var/lib/gems/2.5.0/gems/shopify-cli-1.0.0/lib/shopify-cli/commands/connect.rb:21:in `call'
        12: from /var/lib/gems/2.5.0/gems/shopify-cli-1.0.0/lib/shopify-cli/commands/connect.rb:41:in `fetch_org'
        11: from /var/lib/gems/2.5.0/gems/shopify-cli-1.0.0/lib/shopify-cli/partners_api/organizations.rb:22:in `fetch_with_app'
        10: from /var/lib/gems/2.5.0/gems/shopify-cli-1.0.0/lib/shopify-cli/partners_api.rb:48:in `query'
         9: from /var/lib/gems/2.5.0/gems/shopify-cli-1.0.0/lib/shopify-cli/partners_api.rb:56:in `authenticated_req'
         8: from /var/lib/gems/2.5.0/gems/shopify-cli-1.0.0/lib/shopify-cli/partners_api.rb:49:in `block in query'
         7: from /var/lib/gems/2.5.0/gems/shopify-cli-1.0.0/lib/shopify-cli/partners_api.rb:67:in `api_client'
         6: from /var/lib/gems/2.5.0/gems/shopify-cli-1.0.0/lib/shopify-cli/partners_api.rb:73:in `access_token'
         5: from /var/lib/gems/2.5.0/gems/shopify-cli-1.0.0/lib/shopify-cli/db.rb:87:in `get'
         4: from /var/lib/gems/2.5.0/gems/shopify-cli-1.0.0/lib/shopify-cli/partners_api.rb:74:in `block in access_token'
         3: from /var/lib/gems/2.5.0/gems/shopify-cli-1.0.0/lib/shopify-cli/partners_api.rb:86:in `authenticate'
         2: from /var/lib/gems/2.5.0/gems/shopify-cli-1.0.0/lib/shopify-cli/oauth.rb:43:in `authenticate'
         1: from /var/lib/gems/2.5.0/gems/shopify-cli-1.0.0/lib/shopify-cli/oauth.rb:148:in `request_exchange_token'
/var/lib/gems/2.5.0/gems/shopify-cli-1.0.0/lib/shopify-cli/oauth.rb:169:in `post_token_request': Invalid 'subject_token' value: invalid (ShopifyCli::OAuth::Error)
```

## Specifications

- App type: node
- Operating System: Ubuntu. WSL
- Shell: Bash
- Ruby version (ruby -v): ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-linux-gnu]

**Comment by maxilevi** [comment]
Turns out siging out and siging in again to my shopify account fixed the issue.
