### ISSUE TITLE
Fetch Error after upgrading to 1.4.0

### ISSUE THREAD

**Issue by jlc-christie** [Shopify/shopify-app-cli#933]
# Issue summary
I've been working on an app and the cli has been working perfectly (on 1.3.1), but I just tried to serve the app locally (`shopify serve`) and I got a message saying 1.4.0 was available followed by my ngrok tunnel timing out. I then downloaded the .deb (I'm running Ubuntu) and installed it with dpkg as I have previously. The update seemed to work fine but as soon as I ran shopify serve I repeatedly get an error.

## Expected behavior

Running `shopify serve` updates app url with new ngrok tunnel which I can then use to work on the app

## Actual behavior

I get a fetch error, see error message (didn't put in `<details>` tag because it was messing up the formatting and making it impossible to read):

```
x ngrok tunnel stopped
This command ran with ID: 32577
Please include this information in any issues/report along with relevant logs
Traceback (most recent call last):
	28: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/bin/shopify:32:in `<main>'
	27: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	26: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	25: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/bin/shopify:33:in `block in <main>'
	24: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/lib/shopify-cli/core/entry_point.rb:42:in `call'
	23: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/lib/shopify-cli/core/monorail.rb:20:in `log'
	22: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/lib/shopify-cli/core/entry_point.rb:43:in `block in call'
	21: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/lib/shopify-cli/core/executor.rb:15:in `call'
	20: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
	19: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
	18: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	17: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
	16: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
	15: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
	14: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
	13: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
	12: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/vendor/deps/cli-ui/lib/cli/ui.rb:172:in `log_output_to'
	11: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
	10: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
	 9: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
	 8: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
	 7: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/lib/shopify-cli/command.rb:25:in `call'
	 6: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/lib/project_types/node/commands/serve.rb:15:in `call'
	 5: from /usr/lib/ruby/2.7.0/forwardable.rb:235:in `start'
	 4: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/lib/shopify-cli/tunnel.rb:66:in `start'
	 3: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/lib/shopify-cli/tunnel.rb:163:in `start_ngrok'
	 2: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/lib/shopify-cli/tunnel.rb:147:in `fetch_url'
	 1: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/lib/shopify-cli/tunnel.rb:147:in `new'
/var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/lib/shopify-cli/tunnel.rb:196:in `initialize': Unable to fetch external url (ShopifyCli::Tunnel::FetchUrlError)
	27: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/bin/shopify:32:in `<main>'
	26: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	25: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	24: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/bin/shopify:33:in `block in <main>'
	23: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/lib/shopify-cli/core/entry_point.rb:42:in `call'
	22: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/lib/shopify-cli/core/monorail.rb:20:in `log'
	21: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/lib/shopify-cli/core/entry_point.rb:43:in `block in call'
	20: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/lib/shopify-cli/core/executor.rb:15:in `call'
	19: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
	18: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
	17: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	16: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
	15: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:51:in `twrap'
	14: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
	13: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
	12: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
	11: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/vendor/deps/cli-ui/lib/cli/ui.rb:172:in `log_output_to'
	10: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
	 9: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
	 8: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
	 7: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
	 6: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/lib/shopify-cli/command.rb:25:in `call'
	 5: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/lib/project_types/node/commands/serve.rb:15:in `call'
	 4: from /usr/lib/ruby/2.7.0/forwardable.rb:235:in `start'
	 3: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/lib/shopify-cli/tunnel.rb:66:in `start'
	 2: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/lib/shopify-cli/tunnel.rb:163:in `start_ngrok'
	 1: from /var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/lib/shopify-cli/tunnel.rb:146:in `fetch_url'
/var/lib/gems/2.7.0/gems/shopify-cli-1.4.0/lib/shopify-cli/tunnel.rb:150:in `rescue in fetch_url': Unable to fetch external url `(ShopifyCli::Tunnel::FetchUrlError)`
```

## Steps to reproduce the problem

1. Upgrade to 1.4.0 on Ubuntu
2. Run `shopify serve` in your project

## Specifications

- App type: public
- Operating System: Ubuntu 20.04
- Shell: fish
- Ruby version (ruby -v): `ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]`

**Comment by paulomarg** [comment]
Hi @jlc-christie, thanks for reporting this! As a quick test, if you go back to the previous version - you can download the package from our releases page, uninstall the current one and install the previous one again - does the tunnel start working?

**Comment by jlc-christie** [comment]
@paulomarg just uninstalled 1.4.0 and re-installed 1.3.1 (still had the .deb downloaded). Problem persists, which is strange, as 1.3.1 did work for me beforehand. Could this be local config issue my side? I haven't changed anything since it last worked, however. 

Sorry I can't be of more help, I'm not familiar with Ruby at all.

**Comment by paulomarg** [comment]
It seems that the CLI is not able to start your `ngrok` tunnel, this could be due to network settings (not reaching the ngrok backend), or something is already running on one of the ports used by ngrok. Unfortunately, it's hard to tell why it might be failing, but since it started failing on both versions of the CLI, it's likely failing locally for you.

You could try running the following to see if any specific errors are reported:
```
~/.cache/shopify/ngrok http -inspect=false -log=stdout -log-level=debug <port>
```

You could also make sure that you have read/write permissions on `~/.cache/shopify/sv`, as that's where the CLI will save the log files. 

Hope this helps!

**Comment by jlc-christie** [comment]
@paulomarg 
Thanks for the help with showing where I can run ngrok from, after doing this I discovered that it was ngrok like you suggested. Not sure why but I can't even reach ngrok.com through a browser - maybe some certificate issue or something. Either way, thanks for your help, closing.
